### ISSUE TITLE
Cannot find module "...@vue-storefront/theme-default/webpack.config.js"

### ISSUE THREAD

**Issue by richcrowe** [DivanteLtd/vue-storefront#1054]
Hi!
I can't finish execute the **npm run installer** command because I get an error message **Can't build storefront npm**. In VS logs I did't find any problems and errors, then I went to **./core/scripts/installer** and found there the **npmBuild()** method. OK! 
Then I tried to run  the **npm run build** command in my terminal but I got another error **Cannot find module** but I don't understand what I need to do to fix it.
You can see the logs what I got after execute the ** npm run build ** below

**OS**: OSX
**Node**: 8.11.1
**NPM**: 5.6.0

**npm run build**  terminal
```
> vue-storefront@ build /Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront
> rimraf dist && npm run build:client && npm run build:server


> vue-storefront@ build:client /Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront
> cross-env NODE_ENV=production webpack --config ./core/build/webpack.prod.client.config.js --progress --hide-modules

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront/src/themes/@vue-storefront/theme-default/webpack.config.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront/core/build/webpack.prod.client.config.js:6:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at requireConfig (/Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront/node_modules/webpack/bin/convert-argv.js:96:18)
    at /Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront/node_modules/webpack/bin/convert-argv.js:107:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront@ build:client: `cross-env NODE_ENV=production webpack --config ./core/build/webpack.prod.client.config.js --progress --hide-modules`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-storefront@ build:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/r.crowe/.npm/_logs/2018-04-19T06_26_17_300Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront@ build: `rimraf dist && npm run build:client && npm run build:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-storefront@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/r.crowe/.npm/_logs/2018-04-19T06_26_17_332Z-debug.log

```
**npm run build**  logs
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/r.crowe/.nvm/versions/node/v8.11.1/bin/node',
1 verbose cli   '/Users/r.crowe/.nvm/versions/node/v8.11.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vue-storefront@~prebuild: vue-storefront@
6 info lifecycle vue-storefront@~build: vue-storefront@
7 verbose lifecycle vue-storefront@~build: unsafe-perm in lifecycle true
8 verbose lifecycle vue-storefront@~build: PATH: /Users/r.crowe/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront/node_modules/.bin:/Users/r.crowe/.nvm/versions/node/v8.11.1/bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle vue-storefront@~build: CWD: /Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront
10 silly lifecycle vue-storefront@~build: Args: [ '-c',
10 silly lifecycle   'rimraf dist && npm run build:client && npm run build:server' ]
11 silly lifecycle vue-storefront@~build: Returned: code: 1  signal: null
12 info lifecycle vue-storefront@~build: Failed to exec build script
13 verbose stack Error: vue-storefront@ build: `rimraf dist && npm run build:client && npm run build:server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/r.crowe/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/r.crowe/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid vue-storefront@
15 verbose cwd /Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront
16 verbose Darwin 17.5.0
17 verbose argv "/Users/r.crowe/.nvm/versions/node/v8.11.1/bin/node" "/Users/r.crowe/.nvm/versions/node/v8.11.1/bin/npm" "run" "build"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-storefront@ build: `rimraf dist && npm run build:client && npm run build:server`
22 error Exit status 1
23 error Failed at the vue-storefront@ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
**_______________________________________________**
Also I could post here **npm run installer** logs

Thanks! :)

**Comment by pkarw** [comment]
Hi! It seems like by some reason sth went wrong with the config step of the installer.

What do you have in vue-storefront/config/local.json set as .theme? It should point to "default".

From the error message: '/Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront/src/themes//webpack.config.js'

it seems like theme is by some reason set to '' (it should have been: vue-storefront/src/themes/<default>/webpack.config.js' :)

**Comment by richcrowe** [comment]
![image](https://user-images.githubusercontent.com/26653363/38976057-b26c17d4-43b8-11e8-9c94-74d329be68f2.png)

**Comment by pkarw** [comment]
Could you please change this line in config/default.json to 'default' and rerun installer?

**Comment by pkarw** [comment]
second thing - please check if you have theme-default folder inside vue-storefront/node_modules/@vue-storefront?

**Comment by richcrowe** [comment]
@pkarw ok, now I have ```Error: Cannot find module '/Users/r.crowe/Documents/dev/PHPStorm/magentovue/vue-storefront/src/themes/@vue-storefront/default/webpack.config.js'```

And I no have **../node_modules/@vue-storefront**

**Comment by pkarw** [comment]
shouldn't have happened :) 

OK it seems you need to run "yarn install" - lerna is used to create these virtual modules and it's doing its job on "yarn install" step

**Comment by richcrowe** [comment]
@pkarw omg, this is the best day of my life!
![image](https://user-images.githubusercontent.com/26653363/38977660-aaadc9c0-43bd-11e8-9b20-1834a58d6117.png)
Thank you!

PS I needed to run **yarn install** for @vue-storefront package, but I used **npm install**

**Comment by pkarw** [comment]
That's great! :)
