### ISSUE TITLE
Windows vue-storefront and vue-storefront-api issues

### ISSUE THREAD

**Issue by salmanyaqoobin** [DivanteLtd/vue-storefront#1566]
i am working on windows 10 OS, setup everything as per https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Installing%20on%20Windows.md
i am facing some issues:
on vue-storefront-api when i run the following commad:
command: yarn migrate 
i got following errors:

(node:16172) UnhandledPromiseRejectionWarning: Error: [illegal_argument_exception] Rejecting mapping update to [vue_storefront_catalog] as the final mapping would have more than 1 type: [product, taxrule] :: {"path":"/vue_storefront_catalog/_mapping/taxrule","query":{},"body":"{\"properties\":{\"id\":{\"type\":\"long\"},\"rates\":{\"properties\":{\"rate\":{\"type\":\"float\"}}}}}","statusCode":400,"response":"{\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Rejecting mapping update to [vue_storefront_catalog] as the final mapping would have more than 1 type: [product, taxrule]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"Rejecting mapping update to [vue_storefront_catalog] as the final mapping would have more than 1 type: [product, taxrule]\"},\"status\":400}"}
    at db.indices.putMapping.then.catch.err2 (D:\Workspace\vuejs\vue-storefront-api\src\lib\elastic.js:153:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
and on vue-storefront project after i start the project and browser hit localhost:3000, get the following errors.

{ FetchError: request to http://localhost:8080/api/catalog/vue_storefront_catalog/product/_search?size=8&from=0&sort=created_at%3Adesc&_source_exclude=updated_at%2Ccreated_at%2Cattribu
te_set_id%2Ctier_prices%2Coptions_container%2Cmsrp_display_actual_price_type%2Chas_options%2Cstock.manage_stock%2Cstock.use_config_min_qty%2Cstock.use_config_notify_stock_qty%2Cstock.s
tock_id%2Cstock.use_config_backorders%2Cstock.use_config_enable_qty_inc%2Cstock.enable_qty_increments%2Cstock.use_config_manage_stock%2Cstock.use_config_min_sale_qty%2Cstock.notify_sto
ck_qty%2Cstock.use_config_max_sale_qty%2Cstock.use_config_max_sale_qty%2Cstock.qty_increments%2Csmall_image&_source_include=type_id%2Csku%2Cproduct_links%2Ctax_class_id%2Cspecial_price
%2Cspecial_to_date%2Cspecial_from_date%2Cname%2Cprice%2CpriceInclTax%2CoriginalPriceInclTax%2CoriginalPrice%2CspecialPriceInclTax%2Cid%2Cimage%2Csale%2Cnew%2Curl_key%2Cstatus failed, r
eason: read ECONNRESET
    at ClientRequest.<anonymous> (D:\Workspace\vuejs\vue-storefront-new\node_modules\node-fetch\index.js:133:11)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'FetchError',
  message:
   'request to http://localhost:8080/api/catalog/vue_storefront_catalog/product/_search?size=8&from=0&sort=created_at%3Adesc&_source_exclude=updated_at%2Ccreated_at%2Cattribute_set_id%
2Ctier_prices%2Coptions_container%2Cmsrp_display_actual_price_type%2Chas_options%2Cstock.manage_stock%2Cstock.use_config_min_qty%2Cstock.use_config_notify_stock_qty%2Cstock.stock_id%2C
stock.use_config_backorders%2Cstock.use_config_enable_qty_inc%2Cstock.enable_qty_increments%2Cstock.use_config_manage_stock%2Cstock.use_config_min_sale_qty%2Cstock.notify_stock_qty%2Cs
tock.use_config_max_sale_qty%2Cstock.use_config_max_sale_qty%2Cstock.qty_increments%2Csmall_image&_source_include=type_id%2Csku%2Cproduct_links%2Ctax_class_id%2Cspecial_price%2Cspecial
_to_date%2Cspecial_from_date%2Cname%2Cprice%2CpriceInclTax%2CoriginalPriceInclTax%2CoriginalPrice%2CspecialPriceInclTax%2Cid%2Cimage%2Csale%2Cnew%2Curl_key%2Cstatus failed, reason: rea
d ECONNRESET',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }

**Comment by DavidRouyer** [comment]
`Rejecting mapping update to [vue_storefront_catalog] as the final mapping would have more than 1 type` = You're trying to use Elasticsearch 6.x but Vue Storefront only supports Elasticsearch 5.x (Elasticsearch 6.x introduced a breaking change, they do not support multiple types on the same index)

**Comment by salmanyaqoobin** [comment]
After downgrading the Elasticsearch to 5.x on windows now i am not getting the above error.

On windows power shell when i run the following command i get the error on api project.
command: yarn migrate

{ Error: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="vue_storefront_catalog" & index_uuid="_na_" & index="vue_storefront_catalog" }
    at respond (D:\Workspace\vuejs\vue-storefront-api\node_modules\elasticsearch\src\lib\transport.js:307:15)
    at checkRespForFailure (D:\Workspace\vuejs\vue-storefront-api\node_modules\elasticsearch\src\lib\transport.js:266:7)
    at HttpConnector.<anonymous> (D:\Workspace\vuejs\vue-storefront-api\node_modules\elasticsearch\src\lib\connectors\http.js:159:7)
    at IncomingMessage.bound (D:\Workspace\vuejs\vue-storefront-api\node_modules\elasticsearch\node_modules\lodash\dist\lodash.js:729:21)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 404,
  displayName: 'NotFound',
  message:
   '[index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="vue_storefront_catalog" & index_uuid="_na_" & index="vue_storefront_catalog" }',
  path: '/vue_storefront_catalog/_mapping/product',
  query: {},
  body:
   { error:
      { root_cause: [Array],
        type: 'index_not_found_exception',
        reason: 'no such index',
        'resource.type': 'index_or_alias',
        'resource.id': 'vue_storefront_catalog',
        index_uuid: '_na_',
        index: 'vue_storefront_catalog' },
     status: 404 },
  statusCode: 404,
  response:
   '{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"vue_storefront_catalog","index_uuid":"_na_","in
dex":"vue_storefront_catalog"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"vue_storefront_catalog","index_uuid":"_na_",
"index":"vue_storefront_catalog"},"status":404}',
  toString: [Function],
  toJSON: [Function] }
  error : [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="vue_storefront_catalog" & index_uuid="_na_" & index="vue_storefront_catalog" }
 :: {"path":"/vue_storefront_catalog/_mapping/product","query":{},"body":"{\"properties\":{\"sku\":{\"type\":\"keyword\"},\"size\":{\"type\":\"integer\"},\"size_options\":{\"type\":\"i
nteger\"},\"price\":{\"type\":\"float\"},\"has_options\":{\"type\":\"integer\"},\"special_price\":{\"type\":\"float\"},\"color\":{\"type\":\"integer\"},\"color_options\":{\"type\":\"in
teger\"},\"pattern\":{\"type\":\"text\"},\"id\":{\"type\":\"long\"},\"status\":{\"type\":\"integer\"},\"weight\":{\"type\":\"integer\"},\"visibility\":{\"type\":\"integer\"},\"created_
at\":{\"type\":\"date\",\"format\":\"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis\"},\"updated_at\":{\"type\":\"date\",\"format\":\"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis\"},\"
special_from_date\":{\"type\":\"date\",\"format\":\"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis\"},\"special_to_date\":{\"type\":\"date\",\"format\":\"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd
||epoch_millis\"},\"news_from_date\":{\"type\":\"date\",\"format\":\"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis\"},\"description\":{\"type\":\"text\"},\"name\":{\"type\":\"text\"},\
"configurable_children\":{\"properties\":{\"has_options\":{\"type\":\"boolean\"},\"price\":{\"type\":\"float\"},\"sku\":{\"type\":\"keyword\"}}},\"configurable_options\":{\"properties\
":{\"attribute_id\":{\"type\":\"long\"},\"default_label\":{\"type\":\"text\"},\"label\":{\"type\":\"text\"},\"frontend_label\":{\"type\":\"text\"},\"store_label\":{\"type\":\"text\"},\
"values\":{\"properties\":{\"default_label\":{\"type\":\"text\"},\"label\":{\"type\":\"text\"},\"frontend_label\":{\"type\":\"text\"},\"store_label\":{\"type\":\"text\"},\"value_index\
":{\"type\":\"keyword\"}}}}},\"category_ids\":{\"type\":\"long\"},\"eco_collection\":{\"type\":\"integer\"},\"eco_collection_options\":{\"type\":\"integer\"},\"erin_recommends\":{\"typ
e\":\"integer\"},\"tax_class_id\":{\"type\":\"integer\"},\"position\":{\"type\":\"integer\"},\"required_options\":{\"type\":\"integer\"}}}","statusCode":404,"response":"{\"error\":{\"r
oot_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"vue_storefront_catalog\",\"index_uuid\":\"_na_\
",\"index\":\"vue_storefront_catalog\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"vue_storefront_catal
og\",\"index_uuid\":\"_na_\",\"index\":\"vue_storefront_catalog\"},\"status\":404}"}
error Command failed with exit code 1.
