### ISSUE TITLE
Error: Cannot find module '/vue-storefront/src/themes/@vue-storefront/theme-default/webpack.config.js'

### ISSUE THREAD

**Issue by sebabromberg** [DivanteLtd/vue-storefront#1567]
Fresh install! Commands:
git clone
npm install
npm run dev

Error: Cannot find module '/git/vue-storefront/src/themes/@vue-storefront/theme-default/webpack.config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/git/vue-storefront/core/build/dev-server.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront@ dev: `node ./core/scripts/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-storefront@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    /.npm/_logs/2018-08-09T18_30_02_948Z-debug.log

**Comment by DavidRouyer** [comment]
Try changing the name of your theme in the config from "theme": "@vue-storefront/theme-default" to "theme": "theme-default",

**Comment by pkarw** [comment]
... and use yarn install instead od npm install

**Comment by sebabromberg** [comment]
The name of the template is the original. 

Yarn worked ok for me. What’s the difference? It make not sense. Thank you Piotr.
