### ISSUE TITLE
Build Fails :: Service 'kibana' failed to build, remove x-pack

### ISSUE THREAD

**Issue by rohithwap** [DivanteLtd/vue-storefront#1582]
Docker wasn't starting so I've  run the following

```
chmod 755 /var/run/docker.sock // Change File Permission
sudo usermod -aG docker test // Add user to docker group
```

/vue-storefront$ **npm run installer**

```
Cloning backend into '../vue-storefront-api'...
Trying change directory to '../vue-storefront-api'...
Working in directory '/home/test/web/vue-storefront-api'...
Installing backend npm...
Creating backend config 'config/local.json'...
Starting docker in background...
Error: Can't start docker in background.                                                            
at Promise (/home/test/web/vue-storefront/core/scripts/installer.js:194:16)                 
at new Promise (<anonymous>)                                                                    
at Backend.dockerComposeUp (/home/test/web/vue-storefront/core/scripts/installer.js:190:12) at <anonymous> 
```
**LOG**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'installer' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'preinstaller', 'installer', 'postinstaller' ]
5 info lifecycle vue-storefront@~preinstaller: vue-storefront@
6 info lifecycle vue-storefront@~installer: vue-storefront@
7 verbose lifecycle vue-storefront@~installer: unsafe-perm in lifecycle true
8 verbose lifecycle vue-storefront@~installer: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/test/web/vue-storefront/node_modules/.bin:/usr/local/sbin:/$
9 verbose lifecycle vue-storefront@~installer: CWD: /home/test/web/vue-storefront
10 silly lifecycle vue-storefront@~installer: Args: [ '-c', 'node ./core/scripts/installer' ]
11 silly lifecycle vue-storefront@~installer: Returned: code: 1  signal: null
12 info lifecycle vue-storefront@~installer: Failed to exec installer script
13 verbose stack Error: vue-storefront@ installer: `node ./core/scripts/installer`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid vue-storefront@
15 verbose cwd /home/test/web/vue-storefront
16 verbose Linux 4.4.0-131-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "installer"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-storefront@ installer: `node ./core/scripts/installer`
22 error Exit status 1
23 error Failed at the vue-storefront@ installer script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

/vue-storefront-api$ **docker-compose up -d**
```
Building kibana
Step 1/3 : FROM docker.elastic.co/kibana/kibana:5.6.9
 ---> ac673db3bfb8
Step 2/3 : COPY config/kibana.yml config/kibana.yml
 ---> Using cache
 ---> 7887f97302bf
Step 3/3 : RUN bin/kibana-plugin remove x-pack &&     kibana 2>&1 | grep -m 1 "Optimization of .* complete"
 ---> Running in 80a51f33f4bf
Removing x-pack...
ERROR: Service 'kibana' failed to build: The command '/bin/sh -c bin/kibana-plugin remove x-pack &&     kibana 2>&1 | grep -m 1 "Optimization of .* complete"' returned a non-zero code: 1
```

**Environment:**
`Node v8.11.3 | Docker version 18.06.0-ce, build 0ffa825 | docker-compose version 1.8.0 | 
 Ubuntu 16.04.5 LTS`

**Comment by pszreder** [comment]
@rohithwap I have just checked "docker-compose-up" in the fresh environment (more specifically, building a kibana image). Code taken from the master branch (https://github.com/DivanteLtd/vue-storefront-api.git), no local docker images in the cache:

```
Building kibana
Step 1/3 : FROM docker.elastic.co/kibana/kibana:5.6.9
5.6.9: Pulling from kibana/kibana
469cfcc7a4b3: Pull complete
dbf532e807c5: Pull complete
2fc6a7ee8a3a: Pull complete
aebda185619a: Pull complete
e71a1432017d: Pull complete
5d9b6f46e6f2: Pull complete
0fe8dbe6804f: Pull complete
988ae9a75552: Pull complete
5d502a3ddc8c: Pull complete
Digest: sha256:688a89b16170553566ef6eee7d6698bc83e98d5108cc5a52edf589e22cbb1f26
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:5.6.9
 ---> ac673db3bfb8
Step 2/3 : COPY config/kibana.yml config/kibana.yml
 ---> 12cb8c65520d
Step 3/3 : RUN bin/kibana-plugin remove x-pack &&     kibana 2>&1 | grep -m 1 "Optimization of .* complete"
 ---> Running in 4297ee12deac
Removing x-pack...
{"type":"log","@timestamp":"2018-08-22T11:41:54Z","tags":["info","optimize"],"pid":17,"message":"Optimization of bundles for kibana, stateSessionStorageRedirect, timelion and status_page complete in 100.85 seconds"}
Removing intermediate container 4297ee12deac
 ---> 38d8d00e5573
Successfully built 38d8d00e5573
Successfully tagged vuestorefrontapi_kibana:latest
WARNING: Image for service kibana was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
```

The same docker / docker-compose version as yours.

**Comment by akarso** [comment]
Looks like the issue still persists in latest version. Any Idea what may cause this? 

`Building kibana
Step 1/2 : FROM docker.elastic.co/kibana/kibana:5.6.11
 ---> 72543213daee
Step 2/2 : RUN bin/kibana-plugin remove x-pack &&     kibana 2>&1 | grep -m 1 "Optimization of .* complete"
 ---> Running in f0285d3848a6
Removing x-pack...
`

just hangs on this until server drops connection
