### ISSUE TITLE
install erro ubuntu

### ISSUE THREAD

**Issue by marcelowu** [DivanteLtd/vue-storefront#1633]
![capturar](https://user-images.githubusercontent.com/30912144/44599499-ea2f9300-a7ac-11e8-8732-1df50eedea20.JPG)

Elasticsearch DEBUG: 2018-08-24T17:42:53Z
  Request complete

{ Error: Bad Request
    at respond (/var/www/html/api3/node_modules/elasticsearch/src/lib/transport.js:307:15)
    at checkRespForFailure (/var/www/html/api3/node_modules/elasticsearch/src/lib/transport.js:266:7)
    at HttpConnector.<anonymous> (/var/www/html/api3/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/var/www/html/api3/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  status: 400,
  displayName: 'BadRequest',
  message: 'Bad Request',
  path: '/_reindex',
  query: {},
  body:
   { took: 2020,
     timed_out: false,
     total: 2165,
     updated: 0,
     created: 999,
     deleted: 0,
     batches: 1,
     version_conflicts: 0,
     noops: 0,
     retries: { bulk: 0, search: 0 },
     throttled_millis: 0,
     requests_per_second: -1,
     throttled_until_millis: 0,
     failures: [ [Object] ] },
  statusCode: 400,
  response: '{"took":2020,"timed_out":false,"total":2165,"updated":0,"created":999,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"re$
  toString: [Function],
  toJSON: [Function] }
  ^[[90merror^[[39m : ^[[36mBad Request :: {"path":"/_reindex","query":{},"body":"{\"source\":{\"index\":\"vue_storefront_catalog_temp\"},\"de$
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by pkarw** [comment]
It seems like ElasticSearch is not working or not accepting the requests. Please try to run docker-compose up in the vue-storefront-api and check if there are any errors?
