### ISSUE TITLE
problem during install on windows

### ISSUE THREAD

**Issue by paulvanbladel** [DivanteLtd/vue-storefront#1640]
clean git clone
yarn install
```
$ yarn dev
yarn run v1.9.4
$ node ./core/scripts/server
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'source-list-map'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (E:\GITHUB3RD\vue-storefront\node_modules\webpack-sources\lib\RawSource.js:9:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

$ node -v
v10.9.0

$ yarn -v
1.9.4

$ webpack -v
4.17.1

**Comment by vue-kacper** [comment]
Try: 

`npm i source-list-map`

or yarn syntax equivalent
