### ISSUE TITLE
Issue installing vue storefront with manual method - UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by markoshust** [DivanteLtd/vue-storefront#1801]
## Current behavior
After following the manual method to install, receiving this error:

```
...
app_1  | Hello from example product Vuex action
app_1  | vsf-payment-stripe extension initialised
app_1  | Hello from custom theme extension
app_1  | Entering asyncData for PageNotFound Wed Oct 03 2018 11:07:49 GMT+0000 (UTC)
app_1  | (node:229) UnhandledPromiseRejectionWarning: Error: FetchError: request to http://localhost:8080/api/catalog/vue_storefront_catalog/category/_search?size=4000&from=0&sort=position%3Aasc&_source_include=children_data%2Cid%2Cchildren_count%2Csku%2Cname%2Cis_active%2Cparent_id%2Clevel%2Curl_key%2Cproduct_count failed, reason: connect ECONNREFUSED 127.0.0.1:8080
app_1  | (node:229) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 277)
```

## Expected behavior
Expected compilation step to run without errors

## Steps to reproduce the issue
Follow manual installation method at https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Installing%20on%20Linux%20and%20MacOS.md#manual-installation -- using "standard" mode

localhost:3000 returns "5000 | Internal Server Error" and above error log output on http request

## Enviroment details
Mac OS X High Sierra
Docker 18.06.1-ce-mac73 (26764)

## Additional details
<details>
<summary>full detail log</summary>

```
...
app_1  | Vue Storefront Server started at http://0.0.0.0:3000
app_1  | DEPRECATION WARNING on line 7, column 8 of stdin:
app_1  | Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
app_1  | Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.
app_1  | 
app_1  | DEPRECATION WARNING on line 7, column 8 of stdin:
app_1  | Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
app_1  | Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.
app_1  | 
app_1  | webpack built cec6f59fc0302be3772d in 57069ms
app_1  | ℹ ｢wdm｣: Hash: cec6f59fc0302be3772d
app_1  | Version: webpack 4.20.2
app_1  | Time: 57069ms
app_1  | Built at: 2018-10-03 11:14:28
app_1  |                  Asset      Size           Chunks             Chunk Names
app_1  |             app.js.map  2.23 MiB              app  [emitted]  app
app_1  |                 app.js  2.97 MiB              app  [emitted]  app
app_1  |     lang-es-ES-json.js  22.6 KiB  lang-es-ES-json  [emitted]  lang-es-ES-json
app_1  |     lang-fr-FR-json.js  26.5 KiB  lang-fr-FR-json  [emitted]  lang-fr-FR-json
app_1  |     lang-it-IT-json.js  30.8 KiB  lang-it-IT-json  [emitted]  lang-it-IT-json
app_1  |     lang-jp-JP-json.js  20.3 KiB  lang-jp-JP-json  [emitted]  lang-jp-JP-json
app_1  |     lang-nl-NL-json.js  22.5 KiB  lang-nl-NL-json  [emitted]  lang-nl-NL-json
app_1  |     lang-pl-PL-json.js  27.7 KiB  lang-pl-PL-json  [emitted]  lang-pl-PL-json
app_1  |     lang-pt-BR-json.js  25.2 KiB  lang-pt-BR-json  [emitted]  lang-pt-BR-json
app_1  |     lang-ru-RU-json.js  24.7 KiB  lang-ru-RU-json  [emitted]  lang-ru-RU-json
app_1  |             runtime.js    34 KiB          runtime  [emitted]  runtime
app_1  |              vendor.js   2.7 MiB           vendor  [emitted]  vendor
app_1  |     lang-de-DE-json.js  25.5 KiB  lang-de-DE-json  [emitted]  lang-de-DE-json
app_1  | lang-de-DE-json.js.map  95 bytes  lang-de-DE-json  [emitted]  lang-de-DE-json
app_1  | lang-es-ES-json.js.map  95 bytes  lang-es-ES-json  [emitted]  lang-es-ES-json
app_1  | lang-fr-FR-json.js.map  95 bytes  lang-fr-FR-json  [emitted]  lang-fr-FR-json
app_1  | lang-it-IT-json.js.map  95 bytes  lang-it-IT-json  [emitted]  lang-it-IT-json
app_1  | lang-jp-JP-json.js.map  95 bytes  lang-jp-JP-json  [emitted]  lang-jp-JP-json
app_1  | lang-nl-NL-json.js.map  95 bytes  lang-nl-NL-json  [emitted]  lang-nl-NL-json
app_1  | lang-pl-PL-json.js.map  95 bytes  lang-pl-PL-json  [emitted]  lang-pl-PL-json
app_1  | lang-pt-BR-json.js.map  95 bytes  lang-pt-BR-json  [emitted]  lang-pt-BR-json
app_1  | lang-ru-RU-json.js.map  95 bytes  lang-ru-RU-json  [emitted]  lang-ru-RU-json
app_1  |         runtime.js.map  35.6 KiB          runtime  [emitted]  runtime
app_1  |          vendor.js.map  2.36 MiB           vendor  [emitted]  vendor
app_1  |             index.html  1.82 KiB                   [emitted]  
app_1  | Entrypoint app = runtime.js runtime.js.map vendor.js vendor.js.map app.js app.js.map
app_1  | [./core/app.ts] 2.38 KiB {app} [built]
app_1  | [./core/client-entry.ts] 13 KiB {app} [built]
app_1  | [./core/service-worker-registration.js] 416 bytes {app} [built]
app_1  | [./core/store/lib/multistore.ts] 2.96 KiB {app} [built]
app_1  | [./core/store/lib/storage.ts] 13.3 KiB {app} [built]
app_1  | [./core/store/lib/task.ts] 8.88 KiB {app} [built]
app_1  | [./node_modules/localforage/dist/localforage.js] 90.3 KiB {vendor} [built]
app_1  | [./node_modules/lodash-es/lodash.js] 16.8 KiB {vendor} [built]
app_1  | [./node_modules/strip-ansi/index.js] 161 bytes {vendor} [built]
app_1  | [./node_modules/vue/dist/vue.runtime.esm.js] 207 KiB {vendor} [built]
app_1  | [0] multi webpack-hot-middleware/client ./core/client-entry.ts 40 bytes {app} [built]
app_1  | [./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.16 KiB {vendor} [built]
app_1  | [./node_modules/webpack-hot-middleware/client.js] (webpack)-hot-middleware/client.js 7.59 KiB {vendor} [built]
app_1  | [./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.26 KiB {vendor} [built]
app_1  | [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {vendor} [built]
app_1  |     + 1889 hidden modules
app_1  | Child html-webpack-plugin for "index.html":
app_1  |          Asset     Size  Chunks  Chunk Names
app_1  |     index.html  558 KiB       0  
app_1  |     Entrypoint undefined = index.html
app_1  |     [./node_modules/html-webpack-plugin/lib/loader.js!./src/themes/default/index.template.html] 1.58 KiB {0} [built]
app_1  |     [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
app_1  |     [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
app_1  |     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
app_1  | ℹ ｢wdm｣: Compiled successfully.
app_1  | ℹ ｢wdm｣: Compiling...
app_1  | webpack building...
app_1  | webpack built 73689181b0cc39b9710c in 5872ms
app_1  | ℹ ｢wdm｣: Hash: 73689181b0cc39b9710c
app_1  | Version: webpack 4.20.2
app_1  | Time: 5872ms
app_1  | Built at: 2018-10-03 11:14:39
app_1  |                                      Asset      Size           Chunks             Chunk Names
app_1  |       cec6f59fc0302be3772d.hot-update.json  45 bytes                   [emitted]  
app_1  |       52bd5e5a4a7bd8771175.hot-update.json  44 bytes                   [emitted]  
app_1  |                         lang-de-DE-json.js  25.5 KiB  lang-de-DE-json             lang-de-DE-json
app_1  |                         lang-es-ES-json.js  22.6 KiB  lang-es-ES-json             lang-es-ES-json
app_1  |                         lang-fr-FR-json.js  26.5 KiB  lang-fr-FR-json             lang-fr-FR-json
app_1  |                         lang-it-IT-json.js  30.8 KiB  lang-it-IT-json             lang-it-IT-json
app_1  |                         lang-jp-JP-json.js  20.3 KiB  lang-jp-JP-json             lang-jp-JP-json
app_1  |                         lang-nl-NL-json.js  22.5 KiB  lang-nl-NL-json             lang-nl-NL-json
app_1  |                         lang-pl-PL-json.js  27.7 KiB  lang-pl-PL-json             lang-pl-PL-json
app_1  |                         lang-pt-BR-json.js  25.2 KiB  lang-pt-BR-json             lang-pt-BR-json
app_1  |                         lang-ru-RU-json.js  24.7 KiB  lang-ru-RU-json             lang-ru-RU-json
app_1  |                                 runtime.js    34 KiB          runtime  [emitted]  runtime
app_1  |                                  vendor.js   2.7 MiB           vendor             vendor
app_1  |     app.cec6f59fc0302be3772d.hot-update.js  20.2 KiB              app  [emitted]  app
app_1  |                                     app.js  2.97 MiB              app  [emitted]  app
app_1  |                     lang-de-DE-json.js.map  95 bytes  lang-de-DE-json             lang-de-DE-json
app_1  |                     lang-es-ES-json.js.map  95 bytes  lang-es-ES-json             lang-es-ES-json
app_1  |                     lang-fr-FR-json.js.map  95 bytes  lang-fr-FR-json             lang-fr-FR-json
app_1  |                     lang-it-IT-json.js.map  95 bytes  lang-it-IT-json             lang-it-IT-json
app_1  |                     lang-jp-JP-json.js.map  95 bytes  lang-jp-JP-json             lang-jp-JP-json
app_1  |                     lang-nl-NL-json.js.map  95 bytes  lang-nl-NL-json             lang-nl-NL-json
app_1  |                     lang-pl-PL-json.js.map  95 bytes  lang-pl-PL-json             lang-pl-PL-json
app_1  |                     lang-pt-BR-json.js.map  95 bytes  lang-pt-BR-json             lang-pt-BR-json
app_1  |                     lang-ru-RU-json.js.map  95 bytes  lang-ru-RU-json             lang-ru-RU-json
app_1  |                              vendor.js.map  2.36 MiB           vendor             vendor
app_1  |                                 app.js.map  2.23 MiB              app  [emitted]  app
app_1  | app.cec6f59fc0302be3772d.hot-update.js.map  23.6 KiB              app  [emitted]  app
app_1  |                             runtime.js.map  35.6 KiB          runtime  [emitted]  runtime
app_1  |                                 index.html   1.9 KiB                   [emitted]  
app_1  | Entrypoint app = runtime.js runtime.js.map vendor.js vendor.js.map app.js app.cec6f59fc0302be3772d.hot-update.js app.js.map app.cec6f59fc0302be3772d.hot-update.js.map
app_1  | [./core/app.ts] 2.38 KiB {app}
app_1  | [./core/client-entry.ts] 13 KiB {app} [built]
app_1  | [./core/service-worker-registration.js] 416 bytes {app}
app_1  | [./core/store/lib/multistore.ts] 2.96 KiB {app}
app_1  | [./core/store/lib/storage.ts] 13.3 KiB {app}
app_1  | [./core/store/lib/task.ts] 8.88 KiB {app}
app_1  | [./node_modules/localforage/dist/localforage.js] 90.3 KiB {vendor} [built]
app_1  | [./node_modules/lodash-es/lodash.js] 16.8 KiB {vendor}
app_1  | [./node_modules/strip-ansi/index.js] 161 bytes {vendor} [built]
app_1  | [./node_modules/vue/dist/vue.runtime.esm.js] 207 KiB {vendor} [built]
app_1  | [0] multi webpack-hot-middleware/client ./core/client-entry.ts 40 bytes {app}
app_1  | [./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.16 KiB {vendor} [built]
app_1  | [./node_modules/webpack-hot-middleware/client.js] (webpack)-hot-middleware/client.js 7.59 KiB {vendor} [built]
app_1  | [./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.26 KiB {vendor} [built]
app_1  | [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {vendor}
app_1  |     + 1889 hidden modules
app_1  | Child html-webpack-plugin for "index.html":
app_1  |                                    Asset      Size  Chunks             Chunk Names
app_1  |                               index.html   558 KiB       1             
app_1  |     52bd5e5a4a7bd8771175.hot-update.json  44 bytes          [emitted]  
app_1  |     Entrypoint undefined = index.html
app_1  |     [./node_modules/html-webpack-plugin/lib/loader.js!./src/themes/default/index.template.html] 1.58 KiB {1}
app_1  |     [./node_modules/lodash/lodash.js] 527 KiB {1} [built]
app_1  |     [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {1}
app_1  |     [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {1}
app_1  | ℹ ｢wdm｣: Compiled successfully.
app_1  | Registering Vuex module order
app_1  | Registering Vuex module product
app_1  | Registering Vuex module category
app_1  | Registering Vuex module attribute
app_1  | Registering Vuex module cart
app_1  | Registering Vuex module wishlist
app_1  | Registering Vuex module compare
app_1  | Registering Vuex module user
app_1  | Registering Vuex module payment
app_1  | Registering Vuex module shipping
app_1  | Registering Vuex module ui
app_1  | Registering Vuex module checkout
app_1  | Registering Vuex module homepage
app_1  | Registering Vuex module stock
app_1  | Registering Vuex module tax
app_1  | Registering Vuex module social
app_1  | Registering Vuex module claims
app_1  | Registering Vuex module sync
app_1  | Registering Vuex module promoted
app_1  | Droppoint shipping extension registered
app_1  | Loaded droppoint-shipping
app_1  | Google Analytics extension registered
app_1  | Ensure google analytic account ID is defined in config
app_1  | Loaded google-analytics
app_1  | Cms data extension registered
app_1  | Loaded cms
app_1  | Mailchimp extension registered
app_1  | Loaded mailchimp-subscribe
app_1  | Loaded payment-backend-methods
app_1  | Loaded payment-cash-on-delivery
app_1  | Loaded custom_extension
app_1  | Loaded vsf-payment-stripe
app_1  | Loaded theme_default_example
app_1  | payment-backend-methods extension initialised
app_1  | payment-cash-on-delivery extension initialised
app_1  | Example custom-event added by template example
app_1  | Hello from example product Vuex action
app_1  | vsf-payment-stripe extension initialised
app_1  | Hello from custom theme extension
app_1  | Entering asyncData for Home Wed Oct 03 2018 11:14:39 GMT+0000 (UTC)
app_1  | Error during render : /
app_1  | Error: FetchError: request to http://localhost:8080/api/catalog/vue_storefront_catalog/category/_search?size=4000&from=0&sort=position%3Aasc&_source_include=children_data%2Cid%2Cchildren_count%2Csku%2Cname%2Cis_active%2Cparent_id%2Clevel%2Curl_key%2Cproduct_count failed, reason: connect ECONNREFUSED 127.0.0.1:8080
app_1  |     at _commonErrorHandler (core/server-entry.ts:13:11)
app_1  |     at server-bundle.js:6926:25
app_1  |     at <anonymous>
app_1  |     at process._tickCallback (internal/process/next_tick.js:189:7)
app_1  | Registering Vuex module order
app_1  | Registering Vuex module product
app_1  | Registering Vuex module category
app_1  | Registering Vuex module attribute
app_1  | Registering Vuex module cart
app_1  | Registering Vuex module wishlist
app_1  | Registering Vuex module compare
app_1  | Registering Vuex module user
app_1  | Registering Vuex module payment
app_1  | Registering Vuex module shipping
app_1  | Registering Vuex module ui
app_1  | Registering Vuex module checkout
app_1  | Registering Vuex module homepage
app_1  | Registering Vuex module stock
app_1  | Registering Vuex module tax
app_1  | Registering Vuex module social
app_1  | Registering Vuex module claims
app_1  | Registering Vuex module sync
app_1  | Registering Vuex module promoted
app_1  | Droppoint shipping extension registered
app_1  | Loaded droppoint-shipping
app_1  | Google Analytics extension registered
app_1  | Ensure google analytic account ID is defined in config
app_1  | Loaded google-analytics
app_1  | Cms data extension registered
app_1  | Loaded cms
app_1  | Mailchimp extension registered
app_1  | Loaded mailchimp-subscribe
app_1  | Loaded payment-backend-methods
app_1  | Loaded payment-cash-on-delivery
app_1  | Loaded custom_extension
app_1  | Loaded vsf-payment-stripe
app_1  | Loaded theme_default_example
app_1  | payment-backend-methods extension initialised
app_1  | payment-cash-on-delivery extension initialised
app_1  | Example custom-event added by template example
app_1  | Hello from example product Vuex action
app_1  | vsf-payment-stripe extension initialised
app_1  | Hello from custom theme extension
app_1  | Registering Vuex module order
app_1  | Registering Vuex module product
app_1  | Registering Vuex module category
app_1  | Registering Vuex module attribute
app_1  | Registering Vuex module cart
app_1  | Registering Vuex module wishlist
app_1  | Registering Vuex module compare
app_1  | Registering Vuex module user
app_1  | Registering Vuex module payment
app_1  | Registering Vuex module shipping
app_1  | Registering Vuex module ui
app_1  | Registering Vuex module checkout
app_1  | Registering Vuex module homepage
app_1  | Registering Vuex module stock
app_1  | Registering Vuex module tax
app_1  | Registering Vuex module social
app_1  | Registering Vuex module claims
app_1  | Registering Vuex module sync
app_1  | Registering Vuex module promoted
app_1  | Droppoint shipping extension registered
app_1  | Loaded droppoint-shipping
app_1  | Google Analytics extension registered
app_1  | Ensure google analytic account ID is defined in config
app_1  | Loaded google-analytics
app_1  | Cms data extension registered
app_1  | Loaded cms
app_1  | Mailchimp extension registered
app_1  | Loaded mailchimp-subscribe
app_1  | Loaded payment-backend-methods
app_1  | Loaded payment-cash-on-delivery
app_1  | Loaded custom_extension
app_1  | Loaded vsf-payment-stripe
app_1  | Loaded theme_default_example
app_1  | payment-backend-methods extension initialised
app_1  | payment-cash-on-delivery extension initialised
app_1  | Example custom-event added by template example
app_1  | Hello from example product Vuex action
app_1  | vsf-payment-stripe extension initialised
app_1  | Hello from custom theme extension
app_1  | Entering asyncData for PageNotFound Wed Oct 03 2018 11:14:40 GMT+0000 (UTC)
app_1  | (node:120) UnhandledPromiseRejectionWarning: Error: FetchError: request to http://localhost:8080/api/catalog/vue_storefront_catalog/category/_search?size=4000&from=0&sort=position%3Aasc&_source_include=children_data%2Cid%2Cchildren_count%2Csku%2Cname%2Cis_active%2Cparent_id%2Clevel%2Curl_key%2Cproduct_count failed, reason: connect ECONNREFUSED 127.0.0.1:8080
app_1  | (node:120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 140)
```
</details>

**Comment by pkarw** [comment]
It means that vue-storefront-api is not up and running. Please do check this step: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Installing%20on%20Linux%20and%20MacOS.md#install-the-vue-storefront-api
