### ISSUE TITLE
Error can be repeated

### ISSUE THREAD

**Issue by goodforever** [DivanteLtd/vue-storefront#1973]
After run api and migrate data
docker-compose up vue-storefront
visit localhost:3000  
I got error on homepage ,
"Something went wrong ...
We've noticed Internal Server Error while rendering this request" 
 Then I press home page button (icon button at centre  ) can load all products successfully.  
this error  can be  repeated .
I check log  is 

app_1 | Error during render : /
app_1 | Error: request to http://localhost:8080/api/catalog/vue_storefront_catalog/category/_search?size=4000&from=0&sort=position%3Aasc&_source_include=children_data%2Cid%2Cchildren_count%2Csku%2Cname%2Cis_active%2Cparent_id%2Clevel%2Curl_key%2Cproduct_count%2Cpath failed, reason: connect ECONNREFUSED 127.0.0.1:8080
app_1 | at _commonErrorHandler (core/server-entry.ts:14:11)
app_1 | at server-bundle.js:8843:25
app_1 | at 
app_1 | at process._tickCallback (internal/process/next_tick.js:189:7) 

But if I run  curl to access the same url 

curl -i http://localhost:8080/api/catalog/vue_storefront_catalog/category/_search?size=4000&from=0&sort=position%3Aasc&_source_include=children_data%2Cid%2Cchildren_count%2Csku%2Cname%2Cis_active%2Cparent_id%2Clevel%2Curl_key%2Cproduct_count%2Cpath

I can get data list successfully. that means

**Comment by pkarw** [comment]
`reason: connect ECONNREFUSED 127.0.0.1:8080` means that Your vue-storefront app can not fetch data from vue-storefront-api

**Comment by goodforever** [comment]
@pkarw Thanks !  Do you think what case cause this error ?

**Comment by goodforever** [comment]
@pkarw Yes, I use docker-compose to run  front and back .

**Comment by pkarw** [comment]
Maybe @pszreder would be able to help You with this? I'm not so experienced with docker to be honest

**Comment by goodforever** [comment]
@pkarw Thanks !  maybe,  I know what happened , front maybe dial 127.0.0.1 inside container.

**Comment by goodforever** [comment]
@pkarw It's true

**Comment by mzeis** [comment]
@goodforever How did you solve this?

**Comment by mzeis** [comment]
@pkarw For the record: when using docker to run the frontend and backend, the `vue_storefront` `docker-compose.yml` needs an [external_links](https://docs.docker.com/compose/compose-file/compose-file-v2/#external_links) entry so it can access the `vue_storefront_api` container, e.g.

~~~
diff --git a/docker-compose.yml b/docker-compose.yml
index 3c4598a4..120b2799 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -8,6 +8,8 @@ services:
     env_file: docker/vue-storefront/default.env
     environment:
       VS_ENV: dev
+    external_links:
+      - vue-storefront-api_app_1
     volumes:
       - '.babelrc:/var/www/.babelrc'
       - './config:/var/www/config'
~~~

**Comment by pkarw** [comment]
@mzeis thanks for that, So maybe You'd create a Pull Request with this update? What else it's needed to be updated to make it work out of the box?

**Comment by parnus01** [comment]
> @pkarw For the record: when using docker to run the frontend and backend, the `vue_storefront` `docker-compose.yml` needs an [external_links](https://docs.docker.com/compose/compose-file/compose-file-v2/#external_links) entry so it can access the `vue_storefront_api` container, e.g.
> 
> ```
> diff --git a/docker-compose.yml b/docker-compose.yml
> index 3c4598a4..120b2799 100644
> --- a/docker-compose.yml
> +++ b/docker-compose.yml
> @@ -8,6 +8,8 @@ services:
>      env_file: docker/vue-storefront/default.env
>      environment:
>        VS_ENV: dev
> +    external_links:
> +      - vue-storefront-api_app_1
>      volumes:
>        - '.babelrc:/var/www/.babelrc'
>        - './config:/var/www/config'
> ```

after i add external link , i cannot start container

> ERROR: for vue-storefront_app_1  Cannot create container for service app: b"conflicting options: host type networking can't be used with links. This would result in undefined behavior"

**Comment by pkarw** [comment]
Thanks for reporting this issue! @pszreder can You please take a look at it?

**Comment by parnus01** [comment]
another question how can i see storefront log ? , when i landing into homepage it redirect to error page with Something went wrong ... quote , i already check in var/log it not has anything , 
![screenshot from 2018-12-12 14-57-26](https://user-images.githubusercontent.com/21211130/49854924-40891600-fe1e-11e8-90ae-c0bd74118ce7.png)

**Comment by pkarw** [comment]
The logs are outputted to console standard output/standard error

**Comment by parnus01** [comment]
can't see anything in console log

**Comment by parnus01** [comment]
bankend 
`version: '3.0'
services:

  kibana:
    build: docker/kibana/
    volumes:
      - ./docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - '5601:5601'

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  app:
    # image: divante/vue-storefront-api:latest
    build:
      context: .
      dockerfile: docker/vue-storefront-api/Dockerfile
    depends_on:
      - redis
    env_file: docker/vue-storefront-api/default.env
    environment:
      VS_ENV: dev
    volumes:
      - './config:/var/www/config'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './migrations:/var/www/migrations'
      - './package.json:/var/www/package.json'
      - './scripts:/var/www/scripts'
      - './src:/var/www/src'
      - './var:/var/www/var'
    tmpfs:
      - /var/www/dist
    ports:
      - '8080:8080'

volumes:
  esdat1:
    driver: local
`

frontend
`version: '2.0'
services:
  app:
    # image: divante/vue-storefront:latest
    build:
      context: .
      dockerfile: docker/vue-storefront/Dockerfile
    env_file: docker/vue-storefront/default.env
    environment:
      VS_ENV: dev  
    network_mode: host
    volumes:
      - '.babelrc:/var/www/.babelrc'
      - './config:/var/www/config'
      - './core:/var/www/core'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './.eslintignore:/var/www/.eslintignore'
      - './.eslintrc.js:/var/www/.eslintrc.js'
      - './lerna.json:/var/www/lerna.json'
      - './tsconfig.json:/var/www/tsconfig.json'
      - './shims.d.ts:/var/www/shims.d.ts'
      - './package.json:/var/www/package.json'
      - './src:/var/www/src'
      - './var:/var/www/var'
    tmpfs:
      - /var/www/dist
    ports:
      - '3000:3000'
`

**Comment by parnus01** [comment]
frontend

> version: '2.0'
services:
  app:
    # image: divante/vue-storefront:latest
    build:
      context: .
      dockerfile: docker/vue-storefront/Dockerfile
    env_file: docker/vue-storefront/default.env
    environment:
      VS_ENV: dev  
    network_mode: host
    volumes:
      - '.babelrc:/var/www/.babelrc'
      - './config:/var/www/config'
      - './core:/var/www/core'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './.eslintignore:/var/www/.eslintignore'
      - './.eslintrc.js:/var/www/.eslintrc.js'
      - './lerna.json:/var/www/lerna.json'
      - './tsconfig.json:/var/www/tsconfig.json'
      - './shims.d.ts:/var/www/shims.d.ts'
      - './package.json:/var/www/package.json'
      - './src:/var/www/src'
      - './var:/var/www/var'
    tmpfs:
      - /var/www/dist
    ports:
      - '3000:3000'

backend

> version: '3.0'
services:

  kibana:
    build: docker/kibana/
    volumes:
      - ./docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - '5601:5601'

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'

  app:
    # image: divante/vue-storefront-api:latest
    build:
      context: .
      dockerfile: docker/vue-storefront-api/Dockerfile
    depends_on:
      - redis
    env_file: docker/vue-storefront-api/default.env
    environment:
      VS_ENV: dev
    volumes:
      - './config:/var/www/config'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './migrations:/var/www/migrations'
      - './package.json:/var/www/package.json'
      - './scripts:/var/www/scripts'
      - './src:/var/www/src'
      - './var:/var/www/var'
    tmpfs:
      - /var/www/dist
    ports:
      - '8080:8080'

volumes:
  esdat1:
    driver: local

**Comment by pszreder** [comment]
@parnus01 thanks. In which mode did you start the **API application itself**?
Using our docker environment:
`docker-compose up -f docker-compose.yml -f docker-compose.nodejs.yml -d`
or services inside docker environment:
`docker-compose up -d`
and API application itself natively:
`yarn start`

?

**Comment by parnus01** [comment]
i found the problem elasticsearch container can't start.
after i see logs container

> [2018-12-12T09:32:26,123][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/docker-cluster]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.13.jar:5.6.13]
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/usr/share/elasticsearch/data/docker-cluster]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:265) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.13.jar:5.6.13]
	... 6 more
Caused by: java.io.IOException: failed to obtain lock on /usr/share/elasticsearch/data/nodes/0
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:244) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.13.jar:5.6.13]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.13.jar:5.6.13]
	... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes/0/node.lock
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177) ~[?:?]
	at java.nio.channels.FileChannel.open(FileChannel.java:287) ~[?:1.8.0_191]
	at java.nio.channels.FileChannel.open(FileChannel.java:335) ~[?:1.8.0_191]
	at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:113) ~[lucene-core-6.6.1.jar:6.6.1 9aa465a89b64ff2dabe7b4d50c472de32c298683 - varunthacker - 2017-08-29 21:54:39]

**Comment by pszreder** [comment]
@parnus01 it sounds like your local environment issue...

`maybe these locations are not writable or multiple nodes were started without increasing`

ES container uses named volume "esdat1", by default it's located here on your host:
`/var/lib/docker/volumes/vuestorefrontapi_esdat1`

It definitely has some problem with this volume. Multiple ES container instances running parallel, some permissions issue - I could only guess...

You can try to clean up the ES volume (**be careful if you had some important indices there!**) using this inside API application directory:
`docker-compose down -v`

**Comment by parnus01** [comment]
many thank ! i change permission on this path and it work fine.

**Comment by pszreder** [comment]
@parnus01 no problem.
