### ISSUE TITLE
use redis password

### ISSUE THREAD

**Issue by wubuyun** [DivanteLtd/vue-storefront#1979]
"redis": {
      "host": "localhost",
      "port": 6379,
     "password": xxxxx,
      "db": 0
    },

is correct ?

**Comment by wubuyun** [comment]
{ ReplyError: Ready check failed: NOAUTH Authentication required.
    at parseError (/var/www/html/api/node_modules/redis-parser/lib/parser.js:193:12)
    at parseType (/var/www/html/api/node_modules/redis-parser/lib/parser.js:303:14) command: 'INFO', code: 'NOAUTH' }
