### ISSUE TITLE
Storefront API install issue - Windows

### ISSUE THREAD

**Issue by allenjwelch** [DivanteLtd/vue-storefront#2222]
## Current behavior
Attempting to install vue-storefront-api according to the documentation (https://docs.vuestorefront.io/guide/installation/windows.html#installation-of-vue-storefront-api). 

When running $docker-compose up, docker-compose hangs and last output reads
 "kibana_1  | {"type":"log","@timestamp":"2019-01-17T15:45:41Z","tags":["status","plugin:elasticsearch@5.6.11","info"],"pid":1,"state":"green","message":"Status changed from red to green - Kibana index ready","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}"

Attempted to continue with install in another terminal as documentation suggests, $yarn restore seems to work fine. 

When running $yarn migrate, I receive the following:
yarn run v1.12.3
$ node node_modules/migrate/bin/migrate
Elasticsearch INFO: 2019-01-17T15:33:51Z
  Adding connection to http://localhost:9200/

  up : 1513602693128-create_new_index.js
Elasticsearch DEBUG: 2019-01-17T15:33:51Z
  starting request {
    "method": "DELETE",
    "path": "/*/_alias/vue_storefront_catalog",
    "query": {}
  }

Elasticsearch ERROR: 2019-01-17T15:33:52Z
  Error: Request error, retrying
  DELETE http://localhost:9200/*/_alias/vue_storefront_catalog => connect ECONNREFUSED 127.0.0.1:9200
      at Log.error (C:\Users\EYStudios11\EY-Studios\vue-storefront-api\node_modules\elasticsearch\src\lib\log.js:226:56)
      at checkRespForFailure (C:\Users\EYStudios11\EY-Studios\vue-storefront-api\node_modules\elasticsearch\src\lib\tran
sport.js:259:18)
      at HttpConnector.<anonymous> (C:\Users\EYStudios11\EY-Studios\vue-storefront-api\node_modules\elasticsearch\src\li
b\connectors\http.js:163:7)
      at ClientRequest.wrapper (C:\Users\EYStudios11\EY-Studios\vue-storefront-api\node_modules\lodash\lodash.js:4935:19
)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:392:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
Emitted 'error' event at:
    at RedisClient.<anonymous> (C:\Users\EYStudios11\EY-Studios\vue-storefront-api\node_modules\kue\lib\redis.js:65:13)
    at RedisClient.emit (events.js:182:13)
    at RedisClient.on_error (C:\Users\EYStudios11\EY-Studios\vue-storefront-api\node_modules\redis\index.js:401:14)
    at Socket.<anonymous> (C:\Users\EYStudios11\EY-Studios\vue-storefront-api\node_modules\redis\index.js:279:14)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

## Expected behavior
$docker-compose up and $yarn migrate are not completing.

## Steps to reproduce the issue
Install seems to fail at steps $docker-compose up and $yarn migrate
Running on node version 10.14.0 and Windows 10. I've repeated this several times and tried changing all references to port 9200 with similar errors. 

# Can you handle fixing this bug by yourself?
No

## Environment details
- Browser: Google Chrome v71.0.3578.98
- OS: Windows 10 Home v10.0.17134
- Node:  node version 10.14.0

**Comment by sadaf652** [comment]
having same issue

**Comment by cewald** [comment]
I'm using the docker image for the API.
I noticed that the Redis isn't reachable from the API app container (as you see in the error message). 
When I connect to it and try to connect to _localhost:6379_ with `redis-cli -h localhost` it wont work.

If I use the host from the `docker-compose.yml` file called _"redis"_ (the name of the docker-compose service), it works. So, the default values of the `config/default.json` are not meant to work with the docker images, because
