### ISSUE TITLE
No products found!

### ISSUE THREAD

**Issue by laportem** [DivanteLtd/vue-storefront#2295]
## Current behavior
I’ve been trying to sync data from magneto (CE version 2.3) to VS (release 1.7.0) and for some reasons the Products are not showing up on the screen 

**Categories are visible in the UI but not Products**

I’ve tried both the “Fast integration” and “Manual integration” described in @ [(https://docs.vuestorefront.io/guide/installation/magento.html#integrating-magento2-with-your-local-instance)]

I did not get any errors and checking my ES, I get see that “category” and “product” are in ES
`curl -XPOST 'localhost:9200/vue_storefront_catalog/category/_search'`
`curl -XPOST 'localhost:9200/vue_storefront_catalog/product/_search'`

Any pointers as to why the Products are not showing up when I click on the appropriate Category in VS frontend. BTW, It works ok on the default Magento frontend. Ruled out product setup issue in Magento

`curl -XPOST 'localhost:9200/vue_storefront_catalog/product/_search'`

`
{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":4,"max_score":1.0,"hits":[{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"12","_score":1.0,"_source":{"id":12,"sku":"cavendish_banana","name":"Cavendish Banana","attribute_set_id":4,"price":20,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-25 18:26:53","updated_at":"2019-01-27 13:16:58","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"7","position":10}]},"product_links":[],"options":[],"media_gallery_entries":[{"types":["image","small_image","thumbnail","swatch_image"],"file":"/c/a/cavendish_bananas.jpeg","media_type":"image","disabled":false,"id":5,"label":null,"position":1}],"tier_prices":[],"custom_attributes":null,"final_price":20,"max_price":20,"max_regular_price":20,"minimal_regular_price":20,"special_price":null,"minimal_price":20,"regular_price":20,"image":"/c/a/cavendish_bananas.jpeg","small_image":"/c/a/cavendish_bananas.jpeg","thumbnail":"/c/a/cavendish_bananas.jpeg","swatch_image":"/c/a/cavendish_bananas.jpeg","options_container":"container2","url_key":"cavendish-banana","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Cavendish Banana","meta_keyword":"Cavendish Banana","meta_description":"Cavendish Banana This one is good 1","tax_class_id":"0","category_ids":["7"],"description":"<p>This one is good 1</p>","short_description":"<p>This one is good 2</p>","country_of_manufacture":"SC","size":"4","links":{},"stock":{"item_id":20,"product_id":12,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 13:16:58","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[{"image":"/c/a/cavendish_bananas.jpeg","pos":1,"typ":"image","lab":null}],"category":[{"category_id":7,"name":"Bananas"}],"tsk":1548623855015}},{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"15","_score":1.0,"_source":{"id":15,"sku":"danvers_carrots_jojo","name":"Danvers Carrots","attribute_set_id":4,"price":12,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-27 11:29:36","updated_at":"2019-01-27 11:43:40","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"9","position":0}]},"product_links":[],"options":[],"media_gallery_entries":[],"tier_prices":[],"custom_attributes":null,"final_price":12,"max_price":12,"max_regular_price":12,"minimal_regular_price":12,"special_price":null,"minimal_price":12,"regular_price":12,"options_container":"container2","url_key":"danvers-carrots","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Danvers Carrots","meta_keyword":"Danvers Carrots","meta_description":"Danvers Carrots ","tax_class_id":"0","category_ids":["9"],"links":{},"stock":{"item_id":23,"product_id":15,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 11:43:40","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[],"category":[{"category_id":9,"name":"Carrots"}],"tsk":1548623855015}},{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"16","_score":1.0,"_source":{"id":16,"sku":"Simple Banana","name":"Simple Banana","attribute_set_id":4,"price":121,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-27 20:40:40","updated_at":"2019-01-27 20:41:02","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"7","position":0}]},"product_links":[],"options":[],"media_gallery_entries":[],"tier_prices":[],"custom_attributes":null,"options_container":"container2","url_key":"simple-banana","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Simple Banana","meta_keyword":"Simple Banana","meta_description":"Simple Banana ","tax_class_id":"0","category_ids":["7"],"country_of_manufacture":"SC","size":"4","links":{},"stock":{"item_id":24,"product_id":16,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 20:41:02","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[],"category":[{"category_id":7,"name":"Bananas"}],"tsk":1548623855015}},{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"13","_score":1.0,"_source":{"id":13,"sku":"burro_banana","name":"Burro Banana","attribute_set_id":4,"price":10,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-25 18:39:33","updated_at":"2019-01-27 11:42:41","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"7","position":0}]},"product_links":[],"options":[],"media_gallery_entries":[{"types":["image","small_image","thumbnail","swatch_image"],"file":"/b/u/burro_bananas-1.jpg","media_type":"image","disabled":false,"id":6,"label":null,"position":1}],"tier_prices":[],"custom_attributes":null,"final_price":10,"max_price":10,"max_regular_price":10,"minimal_regular_price":10,"special_price":null,"minimal_price":10,"regular_price":10,"image":"/b/u/burro_bananas-1.jpg","small_image":"/b/u/burro_bananas-1.jpg","thumbnail":"/b/u/burro_bananas-1.jpg","swatch_image":"/b/u/burro_bananas-1.jpg","options_container":"container2","url_key":"burro-banana","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Burro Banana","meta_keyword":"Burro Banana","meta_description":"Burro Banana ddddddd","tax_class_id":"0","category_ids":["7"],"description":"<p>ddddddd</p>","short_description":"<p>eeeeeeeeeeee</p>","links":{},"stock":{"item_id":21,"product_id":13,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 11:42:41","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[{"image":"/b/u/burro_bananas-1.jpg","pos":1,"typ":"image","lab":null}],"category":[{"category_id":7,"name":"Bananas"}],"tsk":1548623855015}}]}}
vagrant@vuestorefront:~/storefront-api$
`

## Environment details
- Browser: Chrome 71
- OS: Ubuntu 18.04 (running in vagrant vsbox)
- Node: 8.10.0
- Magento: 2.3 CE

**Comment by pkarw** [comment]
Thanks for Your report. Sometimes this kind of issues are related to non-applied elastic schema, setting the right types for fields to sort etc you may want to run “yarn db rebuild” in the vue-storefront-api folder to reindex elastic with the right schemes. If it still won’t work afterwards please check if your categories in elastic have the right “url_key” set (the same as it appears in the url) and of products have the correct “category_ids” set

**Comment by pkarw** [comment]
In the attached json I can see that you’ve got “category_ids” assigned but with the “string” data type. Not sure if this could have caused the problem. But to be sure you might want to check the “vue-storefront-api/config/*.product.schema.json” - adding “category_ids” as “int” and running “yarn db rebuild”

**Comment by laportem** [comment]
Thanks. I’ve tried your suggestions without any luck.
However, now, when I click on a category in VSF, in the VSF-API console log I am seeing this error:
`
error: API call failed: The consumer isn't authorized to access self.
(node:16000) UnhandledPromiseRejectionWarning: The consumer isn't authorized to access self.
(node:16000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
`
I can assure you the consumerKey and consumerSecret in both vsf-api/config/local.json and mage2vs/src/config.json are correct and all the API permission options in Magento System/Integrations are checked. 

Is this error related to API access between VSF and VSF-API

**Comment by pkarw** [comment]
This error can be due to unsatisfying permissions set in magento integration - check the settings for customer account orders and other user related settings

However it shouldn’t affect the products. We haven’t tested m2vs against 2.3. If you could send me your integration access details to peter@vuestorefront.io I could try to check it - but I can’t promise when exactly due to other obligations :) thanks!

**Comment by laportem** [comment]
All the API integration permissions are **checked**, and I can use some API (i.e. create/update accounts).
I suspect the issues could be related to the magento 2.3. Will try to lower the magento version and see if the issue goes away

**Comment by pkarw** [comment]
OK, If you could share the accesses that would be awesome as I could port the m2vs to support 2.3 :)

**Comment by pkarw** [comment]
@laportem any update? :)

**Comment by laportem** [comment]
Hi @pkarw, greatly appreciate help with this
I am still trying to debug the issue

Basically, if a point my local VSF-API to **http://demo-magento2.vuestorefront.io**
Everything works ok, I can log in, register new user and browser categories and product

When I switch my VSF-API back to my local Magento (2.3) 
I can log in, register new user, browser categories
**But I cannot see the products under the categories**

I have run `yarn mage2vs import ` in VSF-API (note, I am not using the mage2vuestorefront repo separately to import data as vue-storefront-api included it)
when I run `yarn mage2vs import` in VSF-API, the magento data are imported to my local ES. 

```
http://localhost:5601/app/kibana#/dev_tools/console?_g=()
GET vue_storefront_catalog/category/_search
GET vue_storefront_catalog/product/_search
```
Shows me I have the categories and products synced
**Note**, when I did the `yarn mage2vs import`, I saw the error below but that did not affect the import

```
debug: Calling API endpoint: GET http://192.168.33.41/rest/V1/reviews/?searchCriteria=undefined

2019-01-28T10:55:11.768Z - info:
{ took: 2,
  timed_out: false,
  total: 0,
  deleted: 0,
  batches: 0,
  version_conflicts: 0,
  noops: 0,
  retries: { bulk: 0, search: 0 },
  throttled_millis: 0,
  requests_per_second: -1,
  throttled_until_millis: 0,
  failures: [] }

debug: Response received.

error: API call failed: Request does not match any route.

2019-01-28T10:55:11.921Z - error:
{ message: 'Request does not match any route.',
  stack: 'Error: Request does not match any route.\n    at api.reviews.list.catch (/home/vagrant/storefront-api/node_modules/mage2vuestorefront/src/adapters/magento/review.js:27:13)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)' }

2019-01-28T10:55:11.922Z - info: Task done! Exiting in 30s...
```

I believe the issue is the search api query from VSF and VSF-API. There is a param(s) in this query that is causing the products not to be returned for the selected category.

Still painfully trying to figure out. I may need your help to understand the query

This is the api call VSF fires

`http://localhost:8080/api/catalog/vue_storefront_catalog/product/_search?size=50&from=0&sort=updated_at%3Adesc&_source_exclude=description%2Csgn%2C*.sgn%2Cmsrp_display_actual_price_type%2C*.msrp_display_actual_price_type%2Crequired_options&_source_include=type_id%2Csku%2Cname%2Ctax_class_id%2Cspecial_price%2Cspecial_to_date%2Cspecial_from_date%2Cprice%2CpriceInclTax%2CoriginalPriceInclTax%2CoriginalPrice%2CspecialPriceInclTax%2Cid%2Cimage%2Csale%2Cnew%2Cconfigurable_children.image%2Cconfigurable_children.sku%2Cconfigurable_children.price%2Cconfigurable_children.special_price%2Cconfigurable_children.priceInclTax%2Cconfigurable_children.specialPriceInclTax%2Cconfigurable_children.originalPrice%2Cconfigurable_children.originalPriceInclTax%2Cconfigurable_children.color%2Cconfigurable_children.size%2Cconfigurable_children.id%2Cconfigurable_children.tier_prices%2Cproduct_links%2Curl_key%2Cstatus%2Ctier_prices&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22visibility%22%3A%5B2%2C3%2C4%5D%7D%7D%2C%7B%22terms%22%3A%7B%22status%22%3A%5B0%2C1%5D%7D%7D%2C%7B%22terms%22%3A%7B%22stock.is_in_stock%22%3A%5Btrue%5D%7D%7D%2C%7B%22terms%22%3A%7B%22category_ids%22%3A%5B7%5D%7D%7D%5D%7D%7D%7D%7D%2C%22aggs%22%3A%7B%22agg_terms_color%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22color%22%2C%22size%22%3A10%7D%7D%2C%22agg_terms_color_options%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22color_options%22%2C%22size%22%3A10%7D%7D%2C%22agg_terms_size%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22size%22%2C%22size%22%3A10%7D%7D%2C%22agg_terms_size_options%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22size_options%22%2C%22size%22%3A10%7D%7D%2C%22agg_terms_price%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22price%22%7D%7D%2C%22agg_range_price%22%3A%7B%22range%22%3A%7B%22field%22%3A%22price%22%2C%22ranges%22%3A%5B%7B%22from%22%3A0%2C%22to%22%3A50%7D%2C%7B%22from%22%3A50%2C%22to%22%3A100%7D%2C%7B%22from%22%3A100%2C%22to%22%3A150%7D%2C%7B%22from%22%3A150%7D%5D%7D%7D%2C%22agg_terms_erin_recommends%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22erin_recommends%22%2C%22size%22%3A10%7D%7D%2C%22agg_terms_erin_recommends_options%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22erin_recommends_options%22%2C%22size%22%3A10%7D%7D%7D%7D`

**Comment by laportem** [comment]
Ok, the problem looks to be the changes to Magento 2.3. The ‘is_in_stock’ and ‘qty’ has moved from Product to Assigned Sources (part of the MULTI-SOURCE INVENTORY feature)

mage2vs is not picking up this change and when it syncs the products to local ES, the **stock.is_in_stock** is always defaulted to **false** and **stock.qty = 0** 

VSF includes this query to VSF-API when fetching products

**<root>/core/helpers/index.ts**
```
  if (rootStore.state.config.products.listOutOfStockProducts === false) {
    searchProductQuery = searchProductQuery.applyFilter({key: 'stock.is_in_stock', value: {'eq': true}})
  }
```
Which always return no product

So we need to adjust mage2vs to support Magento 2.3

**Comment by laportem** [comment]
I could but it may takes a while as this is literally my first week playing with VSF and Magento. I need to further familiar myself with the code base for both before confidently providing a fix.

**Comment by rain2o** [comment]
I just ran into a similar issue and wanted to add some info here. 

I have actually been messing around with Magento 2.3 and VSF for the past couple of weeks and I have not run into the `stock.is_in_stock` and `stock.qty` issue at all. I haven't really dug deep into it to find out how/why it _does_ work for me on 2.3 and not for you, but for what it's worth it appears to be loading my Qty in just fine. 

I did however run into the error `error: API call failed: The consumer isn't authorized to access self.` suddenly today on multiple API calls for every page load. After digging in I found it was in fact coming back from Magento, and basically meant that the API integration user didn't have access to the customer's `self` object. The reason for that error is because it was trying to access the customer's cart and other session details. In order to access this you need the customer's authentication, not the Integration/API user. 

I logged out of the customer's session and logged back in and everything went back to working. So it seems the user's session got out of sync somehow - meaning they were still logged in on the VSF side, but their session expired on the Magento side. 

Based on what @laportem has reported there does seem to be a need for some changes to be compatible with 2.3, but it also appears to work for me using 2.3... But there does seem to be an issue with user sessions getting out of sync. Maybe this should be a different issue but as it's the same API error I wanted to share here.

**Comment by pkarw** [comment]
@rain2o the default Magento session timeout I believe is just 60min so it could happen (this issue that you're having is from `vue-storefront-api` either from `mage2vuestorefront` - I believe API, right?)

There is a setting in `vue-storefront` config: `"autoRefreshTokens": true` that should refresh the token whatever it's expiredhttps://github.com/pkarw/vue-storefront/blob/010d2e21dd08a624e69612b4fe0b9175eef486aa/core/lib/sync/task.ts#L69-L70

So You might want to check if it's Your case?
It's not related to M2.3 stock management / MSI.

**Comment by rain2o** [comment]
Thanks @pkarw that makes sense. I had just performed some updates and cleanup on my local so it's possible some weird scenario happened where I cleared some stuff and not others. I'll check on the `autoRefreshTokens`.

And yes, I am running Magento 2.3 and so far have not had any issues with products and stock. If I can provide any further details to help just let me know.

**Comment by pkarw** [comment]
@laportem could You please check if You've got all indexeders updated (https://devdocs.magento.com/guides/v2.3/inventory/):

```
StockItem – Also known as Aggregated Virtual Stock. This is read-only data that the re-indexation process generates. Based on a pre-defined mapping, we define what sources are assigned to the current scope (sales channel) and aggregate quantities from all assigned sources. We also use StockItem to check if a product is in or out of stock. Making this segregation by Read-Only interface (StockItem) and Write-Only interface (SourceItem), the Inventory architecture achieves Command Query Responsibility Segregation (CQRS). As a result, all GET HTTP requests should use StockItem entity, and all POST/PUT should use SourceItem.
```

**Comment by pkarw** [comment]
While there are some ongoing works for MSI support scheduled I’ll switch this “listOutOfStockProducts” to true by default in default.json

**Comment by kipotlea** [comment]
> ## Current behavior
> I’ve been trying to sync data from magneto (CE version 2.3) to VS (release 1.7.0) and for some reasons the Products are not showing up on the screen
> 
> **Categories are visible in the UI but not Products**
> 
> I’ve tried both the “Fast integration” and “Manual integration” described in @ [(https://docs.vuestorefront.io/guide/installation/magento.html#integrating-magento2-with-your-local-instance)]
> 
> I did not get any errors and checking my ES, I get see that “category” and “product” are in ES
> `curl -XPOST 'localhost:9200/vue_storefront_catalog/category/_search'`
> `curl -XPOST 'localhost:9200/vue_storefront_catalog/product/_search'`
> 
> Any pointers as to why the Products are not showing up when I click on the appropriate Category in VS frontend. BTW, It works ok on the default Magento frontend. Ruled out product setup issue in Magento
> 
> `curl -XPOST 'localhost:9200/vue_storefront_catalog/product/_search'`
> 
> `{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":4,"max_score":1.0,"hits":[{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"12","_score":1.0,"_source":{"id":12,"sku":"cavendish_banana","name":"Cavendish Banana","attribute_set_id":4,"price":20,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-25 18:26:53","updated_at":"2019-01-27 13:16:58","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"7","position":10}]},"product_links":[],"options":[],"media_gallery_entries":[{"types":["image","small_image","thumbnail","swatch_image"],"file":"/c/a/cavendish_bananas.jpeg","media_type":"image","disabled":false,"id":5,"label":null,"position":1}],"tier_prices":[],"custom_attributes":null,"final_price":20,"max_price":20,"max_regular_price":20,"minimal_regular_price":20,"special_price":null,"minimal_price":20,"regular_price":20,"image":"/c/a/cavendish_bananas.jpeg","small_image":"/c/a/cavendish_bananas.jpeg","thumbnail":"/c/a/cavendish_bananas.jpeg","swatch_image":"/c/a/cavendish_bananas.jpeg","options_container":"container2","url_key":"cavendish-banana","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Cavendish Banana","meta_keyword":"Cavendish Banana","meta_description":"Cavendish Banana This one is good 1","tax_class_id":"0","category_ids":["7"],"description":"<p>This one is good 1</p>","short_description":"<p>This one is good 2</p>","country_of_manufacture":"SC","size":"4","links":{},"stock":{"item_id":20,"product_id":12,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 13:16:58","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[{"image":"/c/a/cavendish_bananas.jpeg","pos":1,"typ":"image","lab":null}],"category":[{"category_id":7,"name":"Bananas"}],"tsk":1548623855015}},{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"15","_score":1.0,"_source":{"id":15,"sku":"danvers_carrots_jojo","name":"Danvers Carrots","attribute_set_id":4,"price":12,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-27 11:29:36","updated_at":"2019-01-27 11:43:40","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"9","position":0}]},"product_links":[],"options":[],"media_gallery_entries":[],"tier_prices":[],"custom_attributes":null,"final_price":12,"max_price":12,"max_regular_price":12,"minimal_regular_price":12,"special_price":null,"minimal_price":12,"regular_price":12,"options_container":"container2","url_key":"danvers-carrots","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Danvers Carrots","meta_keyword":"Danvers Carrots","meta_description":"Danvers Carrots ","tax_class_id":"0","category_ids":["9"],"links":{},"stock":{"item_id":23,"product_id":15,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 11:43:40","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[],"category":[{"category_id":9,"name":"Carrots"}],"tsk":1548623855015}},{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"16","_score":1.0,"_source":{"id":16,"sku":"Simple Banana","name":"Simple Banana","attribute_set_id":4,"price":121,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-27 20:40:40","updated_at":"2019-01-27 20:41:02","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"7","position":0}]},"product_links":[],"options":[],"media_gallery_entries":[],"tier_prices":[],"custom_attributes":null,"options_container":"container2","url_key":"simple-banana","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Simple Banana","meta_keyword":"Simple Banana","meta_description":"Simple Banana ","tax_class_id":"0","category_ids":["7"],"country_of_manufacture":"SC","size":"4","links":{},"stock":{"item_id":24,"product_id":16,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 20:41:02","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[],"category":[{"category_id":7,"name":"Bananas"}],"tsk":1548623855015}},{"_index":"vue_storefront_catalog_1548591100","_type":"product","_id":"13","_score":1.0,"_source":{"id":13,"sku":"burro_banana","name":"Burro Banana","attribute_set_id":4,"price":10,"status":1,"visibility":4,"type_id":"simple","created_at":"2019-01-25 18:39:33","updated_at":"2019-01-27 11:42:41","extension_attributes":{"website_ids":[1],"category_links":[{"category_id":"7","position":0}]},"product_links":[],"options":[],"media_gallery_entries":[{"types":["image","small_image","thumbnail","swatch_image"],"file":"/b/u/burro_bananas-1.jpg","media_type":"image","disabled":false,"id":6,"label":null,"position":1}],"tier_prices":[],"custom_attributes":null,"final_price":10,"max_price":10,"max_regular_price":10,"minimal_regular_price":10,"special_price":null,"minimal_price":10,"regular_price":10,"image":"/b/u/burro_bananas-1.jpg","small_image":"/b/u/burro_bananas-1.jpg","thumbnail":"/b/u/burro_bananas-1.jpg","swatch_image":"/b/u/burro_bananas-1.jpg","options_container":"container2","url_key":"burro-banana","gift_message_available":"2","required_options":"0","has_options":"0","meta_title":"Burro Banana","meta_keyword":"Burro Banana","meta_description":"Burro Banana ddddddd","tax_class_id":"0","category_ids":["7"],"description":"<p>ddddddd</p>","short_description":"<p>eeeeeeeeeeee</p>","links":{},"stock":{"item_id":21,"product_id":13,"stock_id":1,"qty":0,"is_in_stock":false,"is_qty_decimal":false,"show_default_notification_message":false,"use_config_min_qty":true,"min_qty":0,"use_config_min_sale_qty":1,"min_sale_qty":1,"use_config_max_sale_qty":true,"max_sale_qty":10000,"use_config_backorders":true,"backorders":0,"use_config_notify_stock_qty":true,"notify_stock_qty":1,"use_config_qty_increments":true,"qty_increments":0,"use_config_enable_qty_inc":true,"enable_qty_increments":false,"use_config_manage_stock":true,"manage_stock":true,"low_stock_date":"2019-01-27 11:42:41","is_decimal_divided":false,"stock_status_changed_auto":1},"media_gallery":[{"image":"/b/u/burro_bananas-1.jpg","pos":1,"typ":"image","lab":null}],"category":[{"category_id":7,"name":"Bananas"}],"tsk":1548623855015}}]}} vagrant@vuestorefront:~/storefront-api$`
> 
> ## Environment details
> * Browser: Chrome 71
> * OS: Ubuntu 18.04 (running in vagrant vsbox)
> * Node: 8.10.0
> * Magento: 2.3 CE

I have same problem with this issue @laportem

**Comment by magumbo** [comment]
Just a note on this to anyone else experiencing same issue as I just did. 

The listOutOfStockProducts flag had no effect for me while running the node cli.js products partitions=1, reindexing, flushing cache etc. Showed categories but no products anywhere. I wasn't using MSI. I ended up clearing elasticache and running:

**yarn mage2vs import**

as referenced [here](https://docs.vuestorefront.io/guide/installation/magento.html#fast-integration) instead of the readme instructions listing individual imports [here](https://github.com/DivanteLtd/mage2vuestorefront).

@pkarw Looks like the docs at vuestorefront.io are ahead of the github docs? Might be good to combine, tutorial would be easier to follow from one point. Just a suggestion.

**Comment by pkarw** [comment]
Thanks! @kkdg please check if we need to update the docs
