### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by Decntdefalt** [DivanteLtd/vue-storefront#2377]
Hi!

I've setup vue-storefront with magento before, and i created a new project and ran `node --harmony cli.js fullreindex ` in /mage2vuestorefront/src but this time I'm getting error:

```
debug: Response received.
error: Error occured: Error: unable to verify the first certificate
2019-02-06T10:29:01.905Z - error:  
{ message: 'Error: unable to verify the first certificate',
  stack: 'Error: Error: unable to verify the first certificate\n    at api.products.list.catch (/logima/storefront/logima.io/mage2vuestorefront/src/adapters/magento/product.js:157:15)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)' }
2019-02-06T10:29:01.905Z - info: Cleaning up with tsk = 1549448941812
2019-02-06T10:29:01.906Z - info: Task done! Exiting in 30s...
2019-02-06T10:29:01.910Z - info:  
{ took: 1,
  timed_out: false,
  total: 0,
  deleted: 0,
  batches: 0,
  version_conflicts: 0,
  noops: 0,
  retries: { bulk: 0, search: 0 },
  throttled_millis: 0,
  requests_per_second: -1,
  throttled_until_millis: 0,
```
What does this mean and best way to solve it?

Thanks in advance!

**Comment by Decntdefalt** [comment]
Sorry, I think this is 100% related to not having installed ca-bundle for my magento instance.

**Comment by NuruddinBadawi** [comment]
how did you solve this problem ?
