### ISSUE TITLE
docker-compose up returns Unexpected identifier

### ISSUE THREAD

**Issue by mauveine** [DivanteLtd/vue-storefront#2400]
## Current behavior
When running docker-compose up inside vue-storefront folder it returns this error:
```
app_1  | $ cross-env NODE_ENV=production TS_NODE_PROJECT="tsconfig-build.json" webpack --config ./core/build/webpack.prod.client.config.ts --mode production --progress --hide-modules
app_1  | /var/www/core/build/webpack.prod.client.config.ts:1
app_1  | (function (exports, require, module, __filename, __dirname) { import path from 'path';
app_1  |                                                                      ^^^^
app_1  | 
app_1  | SyntaxError: Unexpected identifier
app_1  |     at new Script (vm.js:79:7)
app_1  |     at NativeCompileCache._moduleCompile (/var/www/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
app_1  |     at Module._compile (/var/www/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
app_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
app_1  |     at Module.load (internal/modules/cjs/loader.js:599:32)
app_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
app_1  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
app_1  |     at Module.require (internal/modules/cjs/loader.js:637:17)
app_1  |     at require (/var/www/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
app_1  |     at WEBPACK_OPTIONS (/var/www/node_modules/webpack-cli/bin/convert-argv.js:115:13)
app_1  |     at requireConfig (/var/www/node_modules/webpack-cli/bin/convert-argv.js:117:6)
app_1  |     at /var/www/node_modules/webpack-cli/bin/convert-argv.js:124:17
app_1  |     at Array.forEach (<anonymous>)
app_1  |     at module.exports (/var/www/node_modules/webpack-cli/bin/convert-argv.js:122:15)
app_1  |     at yargs.parse (/var/www/node_modules/webpack-cli/bin/cli.js:228:39)
app_1  |     at Object.parse (/var/www/node_modules/yargs/yargs.js:567:18)
app_1  |     at /var/www/node_modules/webpack-cli/bin/cli.js:206:8
app_1  |     at Object.<anonymous> (/var/www/node_modules/webpack-cli/bin/cli.js:500:3)
app_1  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
app_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
app_1  |     at Module.load (internal/modules/cjs/loader.js:599:32)
app_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
app_1  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
app_1  |     at Module.require (internal/modules/cjs/loader.js:637:17)
app_1  |     at require (internal/modules/cjs/helpers.js:22:18)
app_1  |     at Object.<anonymous> (/var/www/node_modules/webpack/bin/webpack.js:156:2)
app_1  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
app_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
app_1  |     at Module.load (internal/modules/cjs/loader.js:599:32)
app_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

## Expected behavior
Docker container should be up and running according to the documentation

## Steps to reproduce the issue
Follow standard steps in [here](https://docs.vuestorefront.io/guide/installation/linux-mac.html#install-the-vue-storefront)

# Can you handle fixing this bug by yourself?
No

## Additional information
We followed precisely the instructions from the docs on manual installation.

**Comment by iacopop** [comment]
DAMN. i have the same issue.

**Comment by pkarw** [comment]
Thanks for pointing this out! 
@patzick isn't it related to the TypeScript issue you were working on last week? Could You please double check this one?

**Comment by janmyszkier** [comment]
cannot reproduce on `docker-compose version 1.22.0, build f46880fe`
I think this is already solved and can be closed
