### ISSUE TITLE
storefront installer seems to halt

### ISSUE THREAD

**Issue by 0dp** [DivanteLtd/vue-storefront#2583]
Hi there,
I am trying to install vue-storefront but experience this error

## Environment details

- Browser: N/a
- OS: MacOS 10.14.3
- Node: v11.9.0 

## Current behavior
```
Build storefront npm...
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ERROR                                                                                                               │
│                                                                                                                     │
│ Error: Can't build storefront npm.                                                                                  │
│     at Promise (/vue-storefront-demo/vue-storefront/core/scripts/installer.js:478:16)             │
│     at new Promise (<anonymous>)                                                                                    │
│     at Storefront.npmBuild (/vue-storefront-demo/vue-storefront/core/scripts/installer.js:474:12) │
│                                                                                                                     │
│ Please check log file for details: /vue-storefront-demo/vue-storefront/var/log/install.log
```

install.log
```
Cloning into '../vue-storefront-api'...
npm WARN lifecycle The node binary used for scripts is /var/folders/2m/g2s_zt790dv06fzrg_qn28bw0000gn/T/yarn--1552386594369-0.8316919989310463/node but npm is using /usr/local/Cellar/node/11.9.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> fsevents@1.2.7 install /Users/odp/Desktop/vue-storefront-demo/vue-storefront-api/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/odp/Desktop/vue-storefront-demo/vue-storefront-api/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote

> sharp@0.21.3 install /Users/odp/Desktop/vue-storefront-demo/vue-storefront-api/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /Users/odp/.npm/_libvips/libvips-8.7.0-darwin-x64.tar.gz

> nodemon@1.18.10 postinstall /Users/odp/Desktop/vue-storefront-demo/vue-storefront-api/node_modules/nodemon
> node bin/postinstall || exit 0

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN merge-graphql-schemas@1.5.8 requires a peer of graphql@^0.11.7 || ^0.13.0 || ^14.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

added 985 packages from 698 contributors and audited 11012 packages in 20.954s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN lifecycle The node binary used for scripts is /var/folders/2m/g2s_zt790dv06fzrg_qn28bw0000gn/T/yarn--1552386594369-0.8316919989310463/node but npm is using /usr/local/Cellar/node/11.9.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> vue-storefront-api@0.1.0 restore /Users/odp/Desktop/vue-storefront-demo/vue-storefront-api
> node scripts/elastic.js restore

Tue, 12 Mar 2019 10:30:59 GMT | starting dump
Tue, 12 Mar 2019 10:30:59 GMT | got 100 objects from source file (offset: 0)
Tue, 12 Mar 2019 10:31:00 GMT | sent 100 objects to destination elasticsearch, wrote 100
Tue, 12 Mar 2019 10:31:00 GMT | got 132 objects from source file (offset: 100)
Tue, 12 Mar 2019 10:31:00 GMT | sent 132 objects to destination elasticsearch, wrote 132
Tue, 12 Mar 2019 10:31:00 GMT | got 102 objects from source file (offset: 232)
Tue, 12 Mar 2019 10:31:01 GMT | sent 102 objects to destination elasticsearch, wrote 102
Tue, 12 Mar 2019 10:31:01 GMT | got 104 objects from source file (offset: 334)
Tue, 12 Mar 2019 10:31:01 GMT | sent 104 objects to destination elasticsearch, wrote 104
Tue, 12 Mar 2019 10:31:01 GMT | got 109 objects from source file (offset: 438)
Tue, 12 Mar 2019 10:31:01 GMT | sent 109 objects to destination elasticsearch, wrote 109
Tue, 12 Mar 2019 10:31:01 GMT | got 170 objects from source file (offset: 547)
Tue, 12 Mar 2019 10:31:01 GMT | sent 170 objects to destination elasticsearch, wrote 170
Tue, 12 Mar 2019 10:31:01 GMT | got 106 objects from source file (offset: 717)
Tue, 12 Mar 2019 10:31:01 GMT | sent 106 objects to destination elasticsearch, wrote 106
Tue, 12 Mar 2019 10:31:01 GMT | got 101 objects from source file (offset: 823)
Tue, 12 Mar 2019 10:31:02 GMT | sent 101 objects to destination elasticsearch, wrote 101
Tue, 12 Mar 2019 10:31:02 GMT | got 109 objects from source file (offset: 924)
Tue, 12 Mar 2019 10:31:02 GMT | sent 109 objects to destination elasticsearch, wrote 109
Tue, 12 Mar 2019 10:31:02 GMT | got 108 objects from source file (offset: 1033)
Tue, 12 Mar 2019 10:31:02 GMT | sent 108 objects to destination elasticsearch, wrote 108
Tue, 12 Mar 2019 10:31:02 GMT | got 105 objects from source file (offset: 1141)
Tue, 12 Mar 2019 10:31:02 GMT | sent 105 objects to destination elasticsearch, wrote 105
Tue, 12 Mar 2019 10:31:02 GMT | got 115 objects from source file (offset: 1246)
Tue, 12 Mar 2019 10:31:02 GMT | sent 115 objects to destination elasticsearch, wrote 115
Tue, 12 Mar 2019 10:31:02 GMT | got 103 objects from source file (offset: 1361)
Tue, 12 Mar 2019 10:31:02 GMT | sent 103 objects to destination elasticsearch, wrote 103
Tue, 12 Mar 2019 10:31:02 GMT | got 108 objects from source file (offset: 1464)
Tue, 12 Mar 2019 10:31:03 GMT | sent 108 objects to destination elasticsearch, wrote 108
Tue, 12 Mar 2019 10:31:03 GMT | got 151 objects from source file (offset: 1572)
Tue, 12 Mar 2019 10:31:03 GMT | sent 151 objects to destination elasticsearch, wrote 151
Tue, 12 Mar 2019 10:31:03 GMT | got 125 objects from source file (offset: 1723)
Tue, 12 Mar 2019 10:31:03 GMT | sent 125 objects to destination elasticsearch, wrote 125
Tue, 12 Mar 2019 10:31:03 GMT | got 109 objects from source file (offset: 1848)
Tue, 12 Mar 2019 10:31:03 GMT | sent 109 objects to destination elasticsearch, wrote 109
Tue, 12 Mar 2019 10:31:03 GMT | got 107 objects from source file (offset: 1957)
Tue, 12 Mar 2019 10:31:03 GMT | sent 107 objects to destination elasticsearch, wrote 107
Tue, 12 Mar 2019 10:31:03 GMT | got 177 objects from source file (offset: 2064)
Tue, 12 Mar 2019 10:31:03 GMT | sent 177 objects to destination elasticsearch, wrote 177
Tue, 12 Mar 2019 10:31:03 GMT | got 103 objects from source file (offset: 2241)
Tue, 12 Mar 2019 10:31:03 GMT | sent 103 objects to destination elasticsearch, wrote 103
Tue, 12 Mar 2019 10:31:04 GMT | got 107 objects from source file (offset: 2344)
Tue, 12 Mar 2019 10:31:04 GMT | sent 107 objects to destination elasticsearch, wrote 107
Tue, 12 Mar 2019 10:31:04 GMT | got 120 objects from source file (offset: 2451)
Tue, 12 Mar 2019 10:31:04 GMT | sent 120 objects to destination elasticsearch, wrote 120
Tue, 12 Mar 2019 10:31:04 GMT | got 28 objects from source file (offset: 2571)
Tue, 12 Mar 2019 10:31:04 GMT | sent 28 objects to destination elasticsearch, wrote 28
Tue, 12 Mar 2019 10:31:04 GMT | got 0 objects from source file (offset: 2599)
Tue, 12 Mar 2019 10:31:04 GMT | Total Writes: 2599
Tue, 12 Mar 2019 10:31:04 GMT | dump complete

npm WARN lifecycle The node binary used for scripts is /var/folders/2m/g2s_zt790dv06fzrg_qn28bw0000gn/T/yarn--1552386594369-0.8316919989310463/node but npm is using /usr/local/Cellar/node/11.9.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> vue-storefront-api@0.1.0 migrate /Users/odp/Desktop/vue-storefront-demo/vue-storefront-api
> node node_modules/migrate/bin/migrate

Elasticsearch INFO: 2019-03-12T10:31:05Z
  Adding connection to http://localhost:9200/

  [90mup[39m : [36m1513602693128-create_new_index.js[39m
Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  starting request {
    "method": "DELETE",
    "path": "/*/_alias/vue_storefront_catalog",
    "query": {}
  }


Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  Request complete

Public index alias does not exists [aliases_not_found_exception] aliases [vue_storefront_catalog] missing, with { resource.type="aliases" & resource.id="vue_storefront_catalog" }
Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  starting request {
    "method": "DELETE",
    "path": "/vue_storefront_catalog",
    "query": {}
  }


Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  Request complete

{ acknowledged: [33mtrue[39m }
Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog",
    "body": {
      "settings": {
        "analysis": {
          "tokenizer": {
            "comma": {
              "type": "pattern",
              "pattern": ","
            }
          },
          "analyzer": {
            "comma": {
              "type": "custom",
              "tokenizer": "comma"
            }
          }
        }
      }
    },
    "query": {}
  }


Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  Request complete

{ acknowledged: [33mtrue[39m,
  shards_acknowledged: [33mtrue[39m,
  index: [32m'vue_storefront_catalog'[39m }
  [90mup[39m : [36m1513602868543-change_field_types.js[39m
Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog/_mapping/product",
    "body": {
      "properties": {
        "sku": {
          "type": "keyword"
        },
        "url_key": {
          "type": "keyword"
        },
        "url_path": {
          "type": "keyword"
        },
        "slug": {
          "type": "keyword"
        },
        "size": {
          "type": "integer"
        },
        "size_options": {
          "type": "integer"
        },
        "price": {
          "type": "float"
        },
        "has_options": {
          "type": "integer"
        },
        "special_price": {
          "type": "float"
        },
        "color": {
          "type": "integer"
        },
        "color_options": {
          "type": "integer"
        },
        "pattern": {
          "type": "text"
        },
        "id": {
          "type": "long"
        },
        "status": {
          "type": "integer"
        },
        "weight": {
          "type": "integer"
        },
        "visibility": {
          "type": "integer"
        },
        "created_at": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "updated_at": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "special_from_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "special_to_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "news_from_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "news_to_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "description": {
          "type": "text"
        },
        "name": {
          "type": "text"
        },
        "configurable_children": {
          "properties": {
            "url_key": {
              "type": "keyword"
            },
            "sku": {
              "type": "keyword"
            },
            "has_options": {
              "type": "boolean"
            },
            "price": {
              "type": "float"
            },
            "special_price": {
              "type": "float"
            }
          }
        },
        "configurable_options": {
          "properties": {
            "attribute_id": {
              "type": "long"
            },
            "default_label": {
              "type": "text"
            },
            "label": {
              "type": "text"
            },
            "frontend_label": {
              "type": "text"
            },
            "store_label": {
              "type": "text"
            },
            "values": {
              "properties": {
                "default_label": {
                  "type": "text"
                },
                "label": {
                  "type": "text"
                },
                "frontend_label": {
                  "type": "text"
                },
                "store_label": {
                  "type": "text"
                },
                "value_index": {
                  "type": "keyword"
                }
              }
            }
          }
        },
        "category_ids": {
          "type": "long"
        },
        "eco_collection": {
          "type": "integer"
        },
        "eco_collection_options": {
          "type": "integer"
        },
        "erin_recommends": {
          "type": "integer"
        },
        "tax_class_id": {
          "type": "integer"
        },
        "position": {
          "type": "integer"
        },
        "required_options": {
          "type": "integer"
        },
        "Size_options": {
          "type": "keyword"
        },
        "Color_options": {
          "type": "keyword"
        }
      }
    },
    "query": {}
  }


Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  Request complete

{ acknowledged: [33mtrue[39m }
Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog/_mapping/taxrule",
    "body": {
      "properties": {
        "id": {
          "type": "long"
        },
        "rates": {
          "properties": {
            "rate": {
              "type": "float"
            }
          }
        }
      }
    },
    "query": {}
  }


Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  Request complete

{ acknowledged: [33mtrue[39m }
Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog/_mapping/attribute",
    "body": {
      "properties": {
        "id": {
          "type": "long"
        },
        "attribute_id": {
          "type": "long"
        },
        "options": {
          "properties": {
            "value": {
              "type": "text",
              "index": "not_analyzed"
            }
          }
        }
      }
    },
    "query": {}
  }


Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  Request complete

{ acknowledged: [33mtrue[39m }
Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog/_mapping/cms_page",
    "body": {
      "properties": {
        "id": {
          "type": "long"
        },
        "identifier": {
          "type": "keyword"
        },
        "creation_time": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "update_time": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        }
      }
    },
    "query": {}
  }


Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  Request complete

{ acknowledged: [33mtrue[39m }
Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog/_mapping/cms_block",
    "body": {
      "properties": {
        "id": {
          "type": "long"
        },
        "identifier": {
          "type": "keyword"
        },
        "creation_time": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "update_time": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        }
      }
    },
    "query": {}
  }


Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  Request complete

{ acknowledged: [33mtrue[39m }
Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog/_mapping/category",
    "body": {
      "properties": {
        "url_key": {
          "type": "keyword"
        },
        "url_path": {
          "type": "keyword"
        },
        "slug": {
          "type": "keyword"
        },
        "is_active": {
          "type": "boolean"
        },
        "product_count": {
          "type": "integer"
        },
        "parent_id": {
          "type": "integer"
        },
        "created_at": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "updated_at": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        }
      }
    },
    "query": {}
  }


Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  Request complete

{ acknowledged: [33mtrue[39m }
  [90mup[39m : [36m1513603161654-reindex.js[39m
Elasticsearch DEBUG: 2019-03-12T10:31:05Z
  starting request {
    "method": "POST",
    "path": "/_reindex",
    "body": {
      "source": {
        "index": "vue_storefront_catalog_temp"
      },
      "dest": {
        "index": "vue_storefront_catalog"
      }
    },
    "query": {}
  }


Elasticsearch DEBUG: 2019-03-12T10:31:07Z
  Request complete

{ took: [33m2080[39m,
  timed_out: [33mfalse[39m,
  total: [33m2599[39m,
  updated: [33m0[39m,
  created: [33m2599[39m,
  deleted: [33m0[39m,
  batches: [33m3[39m,
  version_conflicts: [33m0[39m,
  noops: [33m0[39m,
  retries: { bulk: [33m0[39m, search: [33m0[39m },
  throttled_millis: [33m0[39m,
  requests_per_second: [33m-1[39m,
  throttled_until_millis: [33m0[39m,
  failures: [] }
  [90mup[39m : [36m1513603418700-delete_old_index.js[39m
Elasticsearch DEBUG: 2019-03-12T10:31:07Z
  starting request {
    "method": "DELETE",
    "path": "/vue_storefront_catalog_temp",
    "query": {}
  }


Elasticsearch DEBUG: 2019-03-12T10:31:07Z
  Request complete

{ acknowledged: [33mtrue[39m }
  [90mup[39m : [36m1530101328854-local_es_config_fix.js[39m
Searching for deprecated parameters in file '/Users/odp/Desktop/vue-storefront-demo/vue-storefront-api/config/custom-environment-variables.json'...
File '/Users/odp/Desktop/vue-storefront-demo/vue-storefront-api/config/custom-environment-variables.json' updated.
Searching for deprecated parameters in file '/Users/odp/Desktop/vue-storefront-demo/vue-storefront-api/config/local.json'...
File '/Users/odp/Desktop/vue-storefront-demo/vue-storefront-api/config/local.json' updated.
  [90mmigration[39m : [36mcomplete[39m
Cloning into 'var/magento2-sample-data'...
```

Is it timing out? 

Since vue-storefront want node version <11.x I tried to downgrade via brew. That does not seem to change the scenario.

## Environment details Updated

- Browser: N/a
- OS: MacOS 10.14.3
- Node: v10.15.2
- Yarn: v1.13.0

**Comment by filrak** [comment]
Please full the issue template at least with your env details otherwise we can't help you

**Comment by 0dp** [comment]
@filrak apologies,
I didn't think it would fit either a bug or FR.
I've updated OP with env details

**Comment by 0dp** [comment]
I've added some more info related to downgrading node via homebrew

**Comment by pkarw** [comment]
Hi @0dp how are things with this one?

**Comment by 0dp** [comment]
Hey @pkarw

Yarn was just updated on brew to v 1.15.2, so I updated and everything went smooth with the installation

```
┌──────────────────────────────────────────────────────────────────────┐
│ Congratulations!                                                     │
│                                                                      │
│ You've just successfully installed vue-storefront.                   │
│ All required servers are running in background                       │
│                                                                      │
│ Storefront: http://localhost:3000                                    │
│ Backend: http://localhost:8080                                       │
│                                                                      │
│ Logs: /Users/odp/Desktop/vue-storefront-demo/vue-storefront/var/log/ │
│                                                                      │
│ Good Luck!                                                           │
└──────────────────────────────────────────────────────────────────────┘

✨  Done in 172.72s.
```

**Comment by pkarw** [comment]
Great!

**Comment by arimus** [comment]
Just a note for anyone else running into this ticket when finding this problem, without brew being the issue. I mistakenly believed that I could `npm install` instead of `yarn`, so the dependencies didn't get properly installed (as this project is using workspaces) and the build broke when it got to the compilation step.
