### ISSUE TITLE
AMP Product page error

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3227]
## Current behavior

```
TypeError: html.replace is not a function
    at decode (node_modules/lean-he/lib/methods/decode.js:70:0)
    at htmlDecode (core/filters/html-decode.js:8:24)
    at Proxy.render (src/themes/default/components/core/Breadcrumbs.vue?c9b2:33:0)
    at VueComponent.Vue._render (/Users/pkarwatka/Documents/_PROJEKTY/vue-storefront/node_modules/vue/dist/vue.runtime.common.dev.js:3532:22)
    at resolve (/Users/pkarwatka/Documents/_PROJEKTY/vue-storefront/node_modules/vue-server-renderer/build.dev.js:8400:27)
    at waitForServerPrefetch (/Users/pkarwatka/Documents/_PROJEKTY/vue-storefront/node_modules/vue-server-renderer/build.dev.js:8272:3)
    at renderComponentInner (/Users/pkarwatka/Documents/_PROJEKTY/vue-storefront/node_modules/vue-server-renderer/build.dev.js:8411:3)
    at renderComponent (/Users/pkarwatka/Documents/_PROJEKTY/vue-storefront/node_modules/vue-server-renderer/build.dev.js:8368:5)
    at RenderContext.renderNode (/Users/pkarwatka/Documents/_PROJEKTY/vue-storefront/node_modules/vue-server-renderer/build.dev.js:8279:5)
    at RenderContext.next (/Users/pkarwatka/Documents/_PROJEKTY/vue-storefront/node_modules/vue-server-renderer/build.dev.js:2598:23)
```

**Comment by pkarw** [comment]
@przspa can you take a look at this one please?
