### ISSUE TITLE
Invalid / inaccessible index name given in the URL on deploying

### ISSUE THREAD

**Issue by omercan** [DivanteLtd/vue-storefront#3383]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Keep the problem description concise and include:

I deployed the VSF and VSF-API with the documentation. https://docs.vuestorefront.io/guide/installation/production-setup.html#vue-storefront-and-vue-storefront-api

Magento is running on same VPS. But when I check the console I'm getting 500 Internal Server Error on https://dev.xxx.com/api/catalog/api/cart/create?token=

Here is the error, how can I debug it?

`Error: Invalid / inaccessible index name given in the URL. Please do use following URL format: /api/catalog/<index_name>/_search
    at /var/www/vuestorefront/vue-storefront-api/src/api/catalog.js:56:10
    at Layer.handle [as handle_request] (/var/www/vuestorefront/vue-storefront-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/vuestorefront/vue-storefront-api/node_modules/express/lib/router/index.js:317:13)
    at /var/www/vuestorefront/vue-storefront-api/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/vuestorefront/vue-storefront-api/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/vuestorefront/vue-storefront-api/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/var/www/vuestorefront/vue-storefront-api/node_modules/express/lib/router/index.js:174:3)
    at router (/var/www/vuestorefront/vue-storefront-api/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/var/www/vuestorefront/vue-storefront-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/vuestorefront/vue-storefront-api/node_modules/express/lib/router/index.js:317:13)`

**Comment by pkarw** [comment]
It’s 99% that you’ve got different index names in the vs / vsapi config (config/local.json). Check the elasticsearch.indices section - you need to have your index whitelisted in the api. Please check the src code at the position noted in the exception on details how it works: it simply checks if the index name (provided by the frontend app as a query parameter) fits the api config

By the way - please do use forum.vuestorefront.io for this kind of questions.
