### ISSUE TITLE
PM2 configuration for TypeScript

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront#3539]
## What is the motivation for adding / enhancing this feature?

After the recent server modules upgrade the pm2 configuration stopped working as it's not supporting typeScript.

We need to improve it, probably we have just two options:

A) to create another webpack config + build step for compiling `core/scripts/server.ts`; like we have `webpack.prod.sw.config.ts` for the  service workers; this is a recommended way of handling TS in production as it will let us use the ES6 modules from `src/modules/*/server` - this is currently not possible

B) to use the `ts-node` in the ecosystem.json

I've started playing with `ecosystem.json` and this configuration **almost** works:

```json
{
  "apps": [
    {
      "name": "server",
      "max_memory_restart": "1G",
      "instances": "4",
      "exec_mode": "cluster",
      "env": {
        "TS_NODE_PROJECT": "tsconfig-build.json",
        "NODE_ENV": "production"
      },
      "interpreter": "./node_modules/.bin/ts-node",
      "script": "./core/scripts/server.ts",
      "node_args": "--max_old_space_size=1024",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "ignore_watch": [
        "core/build/config.json",
        "node_modules"
      ]
    }
  ]
}

```

... the only missing part is we should add the https://www.npmjs.com/package/tsconfig-paths in order to avoid this error message we're currently getting:

```
/Users/pkarwatka/.pm2/logs/server-error-3.log last 15 lines:
3|server   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
3|server   |     at Module.load (internal/modules/cjs/loader.js:600:32)
3|server   |     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
3|server   |     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
3|server   | Error: Cannot find module 'tsconfig-paths/register'
3|server   |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
3|server   |     at Function.Module._load (internal/modules/cjs/loader.js:508:25)
3|server   |     at Module.require (internal/modules/cjs/loader.js:637:17)
3|server   |     at Function.Module._preloadModules (internal/modules/cjs/loader.js:824:12)
3|server   |     at Object.<anonymous> (/Users/pkarwatka/Documents/_PROJEKTY/vue-storefront/node_modules/ts-node/src/bin.ts:141:17)
3|server   |     at Module._compile (internal/modules/cjs/loader.js:701:30)
3|server   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
3|server   |     at Module.load (internal/modules/cjs/loader.js:600:32)
3|server   |     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
3|server   |     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by lukeromanowicz** [comment]
TS should not be required in yarn:start. I've created a separate bug report #3543
