### ISSUE TITLE
Unable to setup vue-storefront in CentOS7

### ISSUE THREAD

**Issue by razzul** [DivanteLtd/vue-storefront#3564]
<img src="https://raw.githubusercontent.com/razzul/img/master/2019-09-16_200845.png">

**Comment by razzul** [comment]
node -v
**v10.16.0**

yarn -v
**1.17.3**

docker -v
**Docker version 19.03.2, build 6a30dfc**

docker-compose -v
**docker-compose version 1.23.2, build 1110ad01**

cat /etc/centos-release
**CentOS Linux release 7.6.1810 (Core)**

**Comment by martinkosmela** [comment]
You probably need to add your system user to Docker group in order to allow run Docker commands. 

`sudo usermod -aG docker $YOUR_USER
newgrp docker`

I hope it helps.

**Comment by pkarw** [comment]
@razzul please use our https://forum.vuestorefront.io for these questions

**Comment by razzul** [comment]
Hi @martinkosmela 
I was trying to execute "yarn restore" and getting these error messages 

```{ _index: 'vue_storefront_catalog_temp',
  _type: 'product',
  _id: '1973',
  status: 400,
  error:
   { type: 'illegal_argument_exception',
     reason:
      'Rejecting mapping update to [vue_storefront_catalog_temp] as the final mapping would have more than 1 type: [product, attribute]' } }

Done in 11.21s.```


but in my local its totally fine

**Comment by pkarw** [comment]
we don't support ES7 yet - it's in the making: https://github.com/DivanteLtd/vue-storefront-api/pull/342

**Comment by razzul** [comment]
> we don't support ES7 yet - it's in the making: [DivanteLtd/vue-storefront-api#342](https://github.com/DivanteLtd/vue-storefront-api/pull/342)

Hi @pkarw, thanks for the replay but I am not using ES7
```image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1```

**Comment by razzul** [comment]
Can't even do "yarn db rebuild" or "yarn db rebuild -- --indexName=vue_storefront_catalog_1" 

```[karmickdev@host vue-storefront-api]$ yarn db rebuild -- --indexName=vue_storefront_catalog_1
yarn run v1.17.3
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ node scripts/db.js rebuild --indexName=vue_storefront_catalog_1
Elasticsearch INFO: 2019-09-20T13:03:11Z
  Adding connection to http://karmickdev.com:9699/

** Hello! I am going to rebuild EXISTING ES index to fix the schema
** Creating temporary index vue_storefront_catalog_1_1568984592
Elasticsearch DEBUG: 2019-09-20T13:03:11Z
  starting request {
    "method": "DELETE",
    "path": "/*/_alias/vue_storefront_catalog_1_1568984592",
    "query": {}
  }


Elasticsearch DEBUG: 2019-09-20T13:03:11Z
  Request complete

Public index alias does not exists [aliases_not_found_exception] aliases [vue_storefront_catalog_1_1568984592] missing, with { resource.type="aliases" & resource.id="vue_storefront_catalog_1_1568984592" }
Elasticsearch DEBUG: 2019-09-20T13:03:11Z
  starting request {
    "method": "DELETE",
    "path": "/vue_storefront_catalog_1_1568984592",
    "query": {}
  }


Elasticsearch DEBUG: 2019-09-20T13:03:11Z
  Request complete

Elasticsearch DEBUG: 2019-09-20T13:03:11Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog_1_1568984592",
    "body": {
      "settings": {
        "analysis": {
          "tokenizer": {
            "comma": {
              "type": "pattern",
              "pattern": ","
            }
          },
          "analyzer": {
            "comma": {
              "type": "custom",
              "tokenizer": "comma"
            }
          }
        }
      }
    },
    "query": {}
  }


Elasticsearch DEBUG: 2019-09-20T13:03:12Z
  Request complete

{ acknowledged: true,
  shards_acknowledged: true,
  index: 'vue_storefront_catalog_1_1568984592' }
** Putting the mappings on top of vue_storefront_catalog_1_1568984592
Elasticsearch DEBUG: 2019-09-20T13:03:12Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog_1_1568984592/_mapping/product",
    "body": {
      "properties": {
        "sku": {
          "type": "keyword"
        },
        "url_key": {
          "type": "keyword"
        },
        "url_path": {
          "type": "keyword"
        },
        "slug": {
          "type": "keyword"
        },
        "size": {
          "type": "integer"
        },
        "size_options": {
          "type": "integer"
        },
        "price": {
          "type": "float"
        },
        "has_options": {
          "type": "integer"
        },
        "special_price": {
          "type": "float"
        },
        "color": {
          "type": "integer"
        },
        "color_options": {
          "type": "integer"
        },
        "pattern": {
          "type": "text"
        },
        "id": {
          "type": "long"
        },
        "status": {
          "type": "integer"
        },
        "weight": {
          "type": "integer"
        },
        "visibility": {
          "type": "integer"
        },
        "created_at": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "updated_at": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "special_from_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "special_to_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "news_from_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "news_to_date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "description": {
          "type": "text"
        },
        "name": {
          "type": "text"
        },
        "configurable_children": {
          "properties": {
            "url_key": {
              "type": "keyword"
            },
            "sku": {
              "type": "keyword"
            },
            "has_options": {
              "type": "boolean"
            },
            "price": {
              "type": "float"
            },
            "special_price": {
              "type": "float"
            }
          }
        },
        "configurable_options": {
          "properties": {
            "attribute_id": {
              "type": "long"
            },
            "default_label": {
              "type": "text"
            },
            "label": {
              "type": "text"
            },
            "frontend_label": {
              "type": "text"
            },
            "store_label": {
              "type": "text"
            },
            "values": {
              "properties": {
                "default_label": {
                  "type": "text"
                },
                "label": {
                  "type": "text"
                },
                "frontend_label": {
                  "type": "text"
                },
                "store_label": {
                  "type": "text"
                },
                "value_index": {
                  "type": "keyword"
                }
              }
            }
          }
        },
        "category_ids": {
          "type": "long"
        },
        "eco_collection": {
          "type": "integer"
        },
        "eco_collection_options": {
          "type": "integer"
        },
        "erin_recommends": {
          "type": "integer"
        },
        "tax_class_id": {
          "type": "integer"
        },
        "gender": {
          "type": "integer"
        },
        "material": {
          "type": "integer"
        },
        "category_gear": {
          "type": "integer"
        },
        "position": {
          "type": "integer"
        },
        "required_options": {
          "type": "integer"
        },
        "Size_options": {
          "type": "keyword"
        },
        "Color_options": {
          "type": "keyword"
        }
      }
    },
    "query": {}
  }


Elasticsearch DEBUG: 2019-09-20T13:03:12Z
  Request complete

{ acknowledged: true }
Elasticsearch DEBUG: 2019-09-20T13:03:12Z
  starting request {
    "method": "PUT",
    "path": "/vue_storefront_catalog_1_1568984592/_mapping/taxrule",
    "body": {
      "properties": {
        "id": {
          "type": "long"
        },
        "rates": {
          "properties": {
            "rate": {
              "type": "float"
            }
          }
        }
      }
    },
    "query": {}
  }


Elasticsearch DEBUG: 2019-09-20T13:03:12Z
  Request complete

Unhandled Rejection at: Promise [object Promise], reason: Error: [illegal_argument_exception] Rejecting mapping update to [vue_storefront_catalog_1_1568984592] as the final mapping would have more than 1 type: [product, taxrule] :: {"path":"/vue_storefront_catalog_1_1568984592/_mapping/taxrule","query":{},"body":"{\"properties\":{\"id\":{\"type\":\"long\"},\"rates\":{\"properties\":{\"rate\":{\"type\":\"float\"}}}}}","statusCode":400,"response":"{\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Rejecting mapping update to [vue_storefront_catalog_1_1568984592] as the final mapping would have more than 1 type: [product, taxrule]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"Rejecting mapping update to [vue_storefront_catalog_1_1568984592] as the final mapping would have more than 1 type: [product, taxrule]\"},\"status\":400}"}
```

**Comment by pkarw** [comment]
it's compatible only with ES5.6; the https://github.com/DivanteLtd/vue-storefront-api/pull/342 will be compatible from 6> up

**Comment by razzul** [comment]
I am able to run "yarn restore" now, thanks

**Comment by razzul** [comment]
Do you have any idea how to pass token as you can seen in the errro token is missing.


```error: uncaughtException: [security_exception] missing authentication token for REST request [/vue_storefront_catalog/product/2/_update], with { header={ WWW-Authenticate="Basic realm=\"security\" charset=\"UTF-8\"" } } :: {"path":"/vue_storefront_catalog/product/2/_update","query":{},"body":"{\"upsert\":{\"id\":2,\"sku\":\"Test Product\",\"name\":\"Test Product\",\"attribute_set_id\":4,\"price\":10,\"status\":1,\"visibility\":4,\"type_id\":\"simple\",\"created_at\":\"2019-09-19 13:45:50\",\"updated_at\":\"2019-09-19 13:45:50\",\"extension_attributes\":{\"website_ids\":[1],\"category_links\":[{\"position\":0,\"category_id\":\"3\"}]},\"product_links\":[],\"options\":[],\"media_gallery_entries\":[{\"id\":2,\"media_type\":\"image\",\"label\":null,\"position\":1,\"disabled\":false,\"types\":[\"image\",\"small_image\",\"thumbnail\",\"swatch_image\"],\"file\":\"/l/o/logo.gif\"}],\"tier_prices\":[],\"custom_attributes\":null,\"final_price\":10,\"max_price\":10,\"max_regular_price\":10,\"minimal_regular_price\":10,\"special_price\":null,\"minimal_price\":10,\"regular_price\":10,\"image\":\"/l/o/logo.gif\",\"small_image\":\"/l/o/logo.gif\",\"thumbnail\":\"/l/o/logo.gif\",\"swatch_image\":\"/l/o/logo.gif\",\"options_container\":\"container2\",\"msrp_display_actual_price_type\":\"0\",\"url_key\":\"test-product\",\"gift_message_available\":\"2\",\"required_options\":\"0\",\"has_options\":\"0\",\"meta_title\":\"Test Product\",\"meta_keyword\":\"Test Product\",\"meta_description\":\"Test Product \",\"tax_class_id\":\"0\",\"category_ids\":[\"3\"],\"slug\":\"test-product-2\",\"links\":{},\"stock\":{\"item_id\":2,\"product_id\":2,\"stock_id\":1,\"qty\":1000,\"is_in_stock\":true,\"is_qty_decimal\":false,\"show_default_notification_message\":false,\"use_config_min_qty\":true,\"min_qty\":0,\"use_config_min_sale_qty\":1,\"min_sale_qty\":1,\"use_config_max_sale_qty\":true,\"max_sale_qty\":10000,\"use_config_backorders\":true,\"backorders\":0,\"use_config_notify_stock_qty\":true,\"notify_stock_qty\":1,\"use_config_qty_increments\":true,\"qty_increments\":0,\"use_config_enable_qty_inc\":true,\"enable_qty_increments\":false,\"use_config_manage_stock\":true,\"manage_stock\":true,\"low_stock_date\":null,\"is_decimal_divided\":false,\"stock_status_changed_auto\":0},\"media_gallery\":[{\"image\":\"/l/o/logo.gif\",\"pos\":1,\"typ\":\"image\",\"lab\":null,\"vid\":null}],\"category\":[{\"category_id\":3,\"name\":\"Category 1\",\"slug\":\"category-1-3\",\"path\":\"category-1/category-1-3\"}],\"url_path\":\"category-1/category-1-3/test-product-2.html\",\"tsk\":1568987818521},\"doc\":{\"id\":2,\"sku\":\"Test Product\",\"name\":\"Test Product\",\"attribute_set_id\":4,\"price\":10,\"status\":1,\"visibility\":4,\"type_id\":\"simple\",\"created_at\":\"2019-09-19 13:45:50\",\"updated_at\":\"2019-09-19 13:45:50\",\"extension_attributes\":{\"website_ids\":[1],\"category_links\":[{\"position\":0,\"category_id\":\"3\"}]},\"product_links\":[],\"options\":[],\"media_gallery_entries\":[{\"id\":2,\"media_type\":\"image\",\"label\":null,\"position\":1,\"disabled\":false,\"types\":[\"image\",\"small_image\",\"thumbnail\",\"swatch_image\"],\"file\":\"/l/o/logo.gif\"}],\"tier_prices\":[],\"custom_attributes\":null,\"final_price\":10,\"max_price\":10,\"max_regular_price\":10,\"minimal_regular_price\":10,\"special_price\":null,\"minimal_price\":10,\"regular_price\":10,\"image\":\"/l/o/logo.gif\",\"small_image\":\"/l/o/logo.gif\",\"thumbnail\":\"/l/o/logo.gif\",\"swatch_image\":\"/l/o/logo.gif\",\"options_container\":\"container2\",\"msrp_display_actual_price_type\":\"0\",\"url_key\":\"test-product\",\"gift_message_available\":\"2\",\"required_options\":\"0\",\"has_options\":\"0\",\"meta_title\":\"Test Product\",\"meta_keyword\":\"Test Product\",\"meta_description\":\"Test Product \",\"tax_class_id\":\"0\",\"category_ids\":[\"3\"],\"slug\":\"test-product-2\",\"links\":{},\"stock\":{\"item_id\":2,\"product_id\":2,\"stock_id\":1,\"qty\":1000,\"is_in_stock\":true,\"is_qty_decimal\":false,\"show_default_notification_message\":false,\"use_config_min_qty\":true,\"min_qty\":0,\"use_config_min_sale_qty\":1,\"min_sale_qty\":1,\"use_config_max_sale_qty\":true,\"max_sale_qty\":10000,\"use_config_backorders\":true,\"backorders\":0,\"use_config_notify_stock_qty\":true,\"notify_stock_qty\":1,\"use_config_qty_increments\":true,\"qty_increments\":0,\"use_config_enable_qty_inc\":true,\"enable_qty_increments\":false,\"use_config_manage_stock\":true,\"manage_stock\":true,\"low_stock_date\":null,\"is_decimal_divided\":false,\"stock_status_changed_auto\":0},\"media_gallery\":[{\"image\":\"/l/o/logo.gif\",\"pos\":1,\"typ\":\"image\",\"lab\":null,\"vid\":null}],\"category\":[{\"category_id\":3,\"name\":\"Category 1\",\"slug\":\"category-1-3\",\"path\":\"category-1/category-1-3\"}],\"url_path\":\"category-1/category-1-3/test-product-2.html\",\"tsk\":1568987818521}}","statusCode":401,"response":"{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/vue_storefront_catalog/product/2/_update]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/vue_storefront_catalog/product/2/_update]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}","wwwAuthenticateDirective":"Basic realm=\"security\" charset=\"UTF-8\""} date=Fri Sep 20 2019 09:57:03 GMT-0400 (Eastern Daylight Time), pid=14662, uid=1010, gid=1012, cwd=/home/karmickdev/public_html/vue-storefront/vue-storefront-api, execPath=/usr/local/bin/node, version=v10.16.0, argv=[/usr/local/bin/node, /home/karmickdev/public_html/vue-storefront/vue-storefront-api/node_modules/mage2vuestorefront/src/cli.js, products, --removeNonExistent=true, --partitions=1], rss=59564032, heapTotal=44879872, heapUsed=27389648, external=98901, loadavg=[1.654296875, 2.30615234375, 4.27783203125], uptime=330781, trace=[column=15, file=/home/karmickdev/public_html/vue-storefront/vue-storefront-api/node_modules/mage2vuestorefront/src/adapters/nosql/elasticsearch.js, function=null, line=80, method=null, native=false, column=9, file=/home/karmickdev/public_html/vue-storefront/vue-storefront-api/node_modules/elasticsearch/src/lib/transport.js, function=respond, line=327, method=null, native=false, column=7, file=/home/karmickdev/public_html/vue-storefront/vue-storefront-api/node_modules/elasticsearch/src/lib/transport.js, function=checkRespForFailure, line=267, method=null, native=false, column=7, file=/home/karmickdev/public_html/vue-storefront/vue-storefront-api/node_modules/elasticsearch/src/lib/connectors/http.js, function=null, line=166, method=null, native=false, column=19, file=/home/karmickdev/public_html/vue-storefront/vue-storefront-api/node_modules/lodash/lodash.js, function=IncomingMessage.wrapper, line=4929, method=wrapper, native=false, column=15, file=events.js, function=IncomingMessage.emit, line=203, method=emit, native=false, column=12, file=_stream_readable.js, function=endReadableNT, line=1129, method=null, native=false, column=19, file=internal/process/next_tick.js, function=process._tickCallback, line=63, method=_tickCallback, native=false], stack=[Error: [security_exception] missing authentication token for REST request [/vue_storefront_catalog/product/2/_update], with { header={ WWW-Authenticate="Basic realm=\"security\" charset=\"UTF-8\"" } } :: {"path":"/vue_storefront_catalog/product/2/_update","query":{},"body":"{\"upsert\":{\"id\":2,\"sku\":\"Test Product\",\"name\":\"Test Product\",\"attribute_set_id\":4,\"price\":10,\"status\":1,\"visibility\":4,\"type_id\":\"simple\",\"created_at\":\"2019-09-19 13:45:50\",\"updated_at\":\"2019-09-19 13:45:50\",\"extension_attributes\":{\"website_ids\":[1],\"category_links\":[{\"position\":0,\"category_id\":\"3\"}]},\"product_links\":[],\"options\":[],\"media_gallery_entries\":[{\"id\":2,\"media_type\":\"image\",\"label\":null,\"position\":1,\"disabled\":false,\"types\":[\"image\",\"small_image\",\"thumbnail\",\"swatch_image\"],\"file\":\"/l/o/logo.gif\"}],\"tier_prices\":[],\"custom_attributes\":null,\"final_price\":10,\"max_price\":10,\"max_regular_price\":10,\"minimal_regular_price\":10,\"special_price\":null,\"minimal_price\":10,\"regular_price\":10,\"image\":\"/l/o/logo.gif\",\"small_image\":\"/l/o/logo.gif\",\"thumbnail\":\"/l/o/logo.gif\",\"swatch_image\":\"/l/o/logo.gif\",\"options_container\":\"container2\",\"msrp_display_actual_price_type\":\"0\",\"url_key\":\"test-product\",\"gift_message_available\":\"2\",\"required_options\":\"0\",\"has_options\":\"0\",\"meta_title\":\"Test Product\",\"meta_keyword\":\"Test Product\",\"meta_description\":\"Test Product \",\"tax_class_id\":\"0\",\"category_ids\":[\"3\"],\"slug\":\"test-product-2\",\"links\":{},\"stock\":{\"item_id\":2,\"product_id\":2,\"stock_id\":1,\"qty\":1000,\"is_in_stock\":true,\"is_qty_decimal\":false,\"show_default_notification_message\":false,\"use_config_min_qty\":true,\"min_qty\":0,\"use_config_min_sale_qty\":1,\"min_sale_qty\":1,\"use_config_max_sale_qty\":true,\"max_sale_qty\":10000,\"use_config_backorders\":true,\"backorders\":0,\"use_config_notify_stock_qty\":true,\"notify_stock_qty\":1,\"use_config_qty_increments\":true,\"qty_increments\":0,\"use_config_enable_qty_inc\":true,\"enable_qty_increments\":false,\"use_config_manage_stock\":true,\"manage_stock\":true,\"low_stock_date\":null,\"is_decimal_divided\":false,\"stock_status_changed_auto\":0},\"media_gallery\":[{\"image\":\"/l/o/logo.gif\",\"pos\":1,\"typ\":\"image\",\"lab\":null,\"vid\":null}],\"category\":[{\"category_id\":3,\"name\":\"Category 1\",\"slug\":\"category-1-3\",\"path\":\"category-1/category-1-3\"}],\"url_path\":\"category-1/category-1-3/test-product-2.html\",\"tsk\":1568987818521},\"doc\":{\"id\":2,\"sku\":\"Test Product\",\"name\":\"Test Product\",\"attribute_set_id\":4,\"price\":10,\"status\":1,\"visibility\":4,\"type_id\":\"simple\",\"created_at\":\"2019-09-19 13:45:50\",\"updated_at\":\"2019-09-19 13:45:50\",\"extension_attributes\":{\"website_ids\":[1],\"category_links\":[{\"position\":0,\"category_id\":\"3\"}]},\"product_links\":[],\"options\":[],\"media_gallery_entries\":[{\"id\":2,\"media_type\":\"image\",\"label\":null,\"position\":1,\"disabled\":false,\"types\":[\"image\",\"small_image\",\"thumbnail\",\"swatch_image\"],\"file\":\"/l/o/logo.gif\"}],\"tier_prices\":[],\"custom_attributes\":null,\"final_price\":10,\"max_price\":10,\"max_regular_price\":10,\"minimal_regular_price\":10,\"special_price\":null,\"minimal_price\":10,\"regular_price\":10,\"image\":\"/l/o/logo.gif\",\"small_image\":\"/l/o/logo.gif\",\"thumbnail\":\"/l/o/logo.gif\",\"swatch_image\":\"/l/o/logo.gif\",\"options_container\":\"container2\",\"msrp_display_actual_price_type\":\"0\",\"url_key\":\"test-product\",\"gift_message_available\":\"2\",\"required_options\":\"0\",\"has_options\":\"0\",\"meta_title\":\"Test Product\",\"meta_keyword\":\"Test Product\",\"meta_description\":\"Test Product \",\"tax_class_id\":\"0\",\"category_ids\":[\"3\"],\"slug\":\"test-product-2\",\"links\":{},\"stock\":{\"item_id\":2,\"product_id\":2,\"stock_id\":1,\"qty\":1000,\"is_in_stock\":true,\"is_qty_decimal\":false,\"show_default_notification_message\":false,\"use_config_min_qty\":true,\"min_qty\":0,\"use_config_min_sale_qty\":1,\"min_sale_qty\":1,\"use_config_max_sale_qty\":true,\"max_sale_qty\":10000,\"use_config_backorders\":true,\"backorders\":0,\"use_config_notify_stock_qty\":true,\"notify_stock_qty\":1,\"use_config_qty_increments\":true,\"qty_increments\":0,\"use_config_enable_qty_inc\":true,\"enable_qty_increments\":false,\"use_config_manage_stock\":true,\"manage_stock\":true,\"low_stock_date\":null,\"is_decimal_divided\":false,\"stock_status_changed_auto\":0},\"media_gallery\":[{\"image\":\"/l/o/logo.gif\",\"pos\":1,\"typ\":\"image\",\"lab\":null,\"vid\":null}],\"category\":[{\"category_id\":3,\"name\":\"Category 1\",\"slug\":\"category-1-3\",\"path\":\"category-1/category-1-3\"}],\"url_path\":\"category-1/category-1-3/test-product-2.html\",\"tsk\":1568987818521}}","statusCode":401,"response":"{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/vue_storefront_catalog/product/2/_update]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/vue_storefront_catalog/product/2/_update]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}","wwwAuthenticateDirective":"Basic realm=\"security\" charset=\"UTF-8\""},     at /home/karmickdev/public_html/vue-storefront/vue-storefront-api/node_modules/mage2vuestorefront/src/adapters/nosql/elasticsearch.js:80:15,     at respond (/home/karmickdev/public_html/vue-storefront/vue-storefront-api/node_modules/elasticsearch/src/lib/transport.js:327:9),     at checkRespForFailure (/home/karmickdev/public_html/vue-storefront/vue-storefront-api/node_modules/elasticsearch/src/lib/transport.js:267:7),     at HttpConnector.<anonymous> (/home/karmickdev/public_html/vue-storefront/vue-storefront-api/node_modules/elasticsearch/src/lib/connectors/http.js:166:7),     at IncomingMessage.wrapper (/home/karmickdev/public_html/vue-storefront/vue-storefront-api/node_modules/lodash/lodash.js:4929:19),     at IncomingMessage.emit (events.js:203:15),     at endReadableNT (_stream_readable.js:1129:12),     at process._tickCallback (internal/process/next_tick.js:63:19)]
```

**Comment by razzul** [comment]
Hi @pkarw, thanks for your support is now running in our stage server
http://karmickdev.com:3001
