### ISSUE TITLE
ERROR: "wrong version number:../ssl/record/ssl3_record"

### ISSUE THREAD

**Issue by JuliaBonita** [DivanteLtd/vue-storefront#3814]
I've been troubleshooting VSF for days. Before I deploy to a production server, I'm trying to practice deploying to localhost. (I can't use Docker for this project.) I've resolved almost every issue, but this "wrong version number:../ssl/record/ssl3_record" error will not go away. Here's the pm2 log data:
```
3|server   | 2019-11-15 03:36:19: Error: FetchError in request to ES: FetchError: request to https://store.localhost:8080/api/catalog/vue_storefront_catalog/product/_search?_source_exclude=%2A.msrp_display_actual_price_type%2Crequired_options%2Cupdated_at%2Ccreated_at%2Cattribute_set_id%2Coptions_container%2Cmsrp_display_actual_price_type%2Chas_options%2Cstock.manage_stock%2Cstock.use_config_min_qty%2Cstock.use_config_notify_stock_qty%2Cstock.stock_id%2Cstock.use_config_backorders%2Cstock.use_config_enable_qty_inc%2Cstock.enable_qty_increments%2Cstock.use_config_manage_stock%2Cstock.use_config_min_sale_qty%2Cstock.notify_stock_qty%2Cstock.use_config_max_sale_qty%2Cstock.use_config_max_sale_qty%2Cstock.qty_increments%2Csmall_image%2Csgn%2C%2A.sgn&from=0&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22category.name.keyword%22%3A%5B%22Tees%22%5D%7D%7D%2C%7B%22terms%22%3A%7B%22visibility%22%3A%5B2%2C3%2C4%5D%7D%7D%2C%7B%22terms%22%3A%7B%22status%22%3A%5B0%2C1%5D%7D%7D%5D%7D%7D%7D%7D%7D&size=8&sort=created_at%3Adesc failed, reason: write EPROTO 140344968678400:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
3|server   |     at w (core/server-entry.ts:23:25)
3|server   |     at server-bundle.js:1:468554
3|server   |     at process._tickCallback (internal/process/next_tick.js:68:7)
4|server   | 2019-11-15 03:36:19: whole request [/error]: 219ms


│ App name │ id │ mode    │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user     │ watching │
├──────────┼────┼─────────┼──────┼────────┼─────────┼────────┼─────┼───────────┼──────────┼──────────┤
│ api      │ 0  │ fork    │ 4517 │ online │ 0       │ 3s     │ 41% │ 93.7 MB   │ www-data │ disabled │
│ o2m      │ 1  │ fork    │ 4518 │ online │ 0       │ 3s     │ 28% │ 70.3 MB   │ www-data │ disabled │
│ server   │ 2  │ cluster │ 4529 │ online │ 0       │ 3s     │ 32% │ 78.1 MB   │ www-data │ disabled │
│ server   │ 3  │ cluster │ 4530 │ online │ 0       │ 3s     │ 34% │ 83.3 MB   │ www-data │ disabled │
│ server   │ 4  │ cluster │ 4647 │ online │ 0       │ 2s     │ 27% │ 37.5 MB   │ www-data │ disabled │
│ server   │ 5  │ cluster │ 4676 │ online │ 0       │ 1s     │ 27% │ 33.9 MB   │ www-data │ disabled │

```

I have already confirmed that the self-signed SSL certificate works fine for all the other localhost domains including the plain Magento store and PhpMyAdmin and others. This is also confirmed because the `yarn mage2vs import` command was successful with https://m2.localhost, which would not be successful if the SSL certificate was invalid. So, there's nothing wrong with the Magento installation and there's nothing wrong with the SSL certificate. But the VSF Chrome log says the issue is the certificate:

### **Chrome Console Errors:**
```
VM362:1 OPTIONS https://store.localhost:8080/api/cart/create?token= net::ERR_SSL_PROTOCOL_ERROR
(anonymous) @ VM362:1
x @ task.ts:65
(anonymous) @ task.ts:175
C @ task.ts:174
(anonymous) @ index.ts:40
........
An SSL certificate error occurred when fetching the script.
```

So, clearly there is a problem with the SSL connection between the VSF app and VSF API, but my config files are configured exactly the way the example files are, but with localhost. Here are all my config files:

### **Nginx Configs:**
```
server {

# Redirect all non-HTTPS requests.
	listen 80;
	server_name store.localhost; 	
	return 301 https://store.localhost$request_uri;
}

server {
	
    listen 443 ssl http2;
    server_name store.localhost;
    ssl_certificate /etc/ssl/certs/server.crt;
    ssl_certificate_key /etc/ssl/private/server.key;
    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
	ssl_prefer_server_ciphers on;	
	ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA;
	ssl_ecdh_curve secp384r1;
	ssl_session_timeout 10m;
	ssl_session_cache shared:SSL:10m;
	ssl_session_tickets off;
	ssl_stapling on;
	ssl_stapling_verify on;
	resolver 8.8.8.8 8.8.4.4 valid=300s;
	resolver_timeout 5s; 

	ssl_dhparam /etc/nginx/ssl/dhparam.pem;

	add_header Strict-Transport-Security "max-age=31536000" always;
	add_header X-Frame-Options DENY;
	add_header X-Content-Type-Options nosniff;
	add_header X-XSS-Protection "1; mode=block";
	add_header X-Robots-Tag none; 

	gzip on;
	gzip_proxied any;
	gzip_types
		text/css
		text/javascript
		application/javascript
		application/json
    text/xml
		text/json;

# The proxy_pass configs pull the content from the Node.js server running on 
# localhost into Nginx. Then Nginx redirects the content to the simple URLs 
# without the port numbers. This creates some protection by hiding the service 
# ports and forcing all requests to be handled by Nginx, which is a more robust 
# HTTP server.

	location / {
		proxy_pass http://localhost:3000/;
	}

	location /assets/ {
		proxy_pass http://localhost:3000/assets/;
	}

   location /api/ {
		proxy_pass http://localhost:8080/api/;
	}

   location /graphql {
		proxy_pass http://localhost:8080/graphql;
	}
  
   location /img/ {
		proxy_pass http://localhost:8080/img/;
	}
}
```

### **vue-storefront-api/config/local.json**
```
{{
    "port": 8080,
    "objHashSecret": "__SECRET_CHANGE_ME__",
    "bodyLimit": "100kb",
    "corsHeaders": [
        "Link"
    ],
    "kue": {},
    "tax": {
        "defaultCountry": "PL",
        "defaultRegion": "",
        "calculateServerSide": true
    },
    "platform": "magento2",
    "registeredExtensions": [
        "mailchimp-subscribe"
    ],
    "extensions": {
        "mailchimp": {
            "listId": "e06875a7e1",
            "apiKey": "a9a3318ea7d30f5c5596bd4a78ae0985-us3",
            "apiUrl": "https://us3.api.mailchimp.com/3.0"
        }
    },
    "magento2": {
        "url": "https://m2.localhost/",
        "imgUrl": "https://m2.localhost/media/catalog/product",
        "magentoUserName": "",
        "magentoUserPassword": "",
        "httpUserName": "",
        "httpUserPassword": "",
        "api": {
            "url": "https://m2.localhost/rest",
            "consumerKey": "ejfqnbpiey5v8j8qrvbt6t0vrwymjqdw",
            "consumerSecret": "h5cxj3rqsmw2ll7lu0r82m89obqvy4kc",
            "accessToken": "yqk7bqtyva88o1ivqqqwug1rtr8wgsrt",
            "accessTokenSecret": "3sb5tlyv7bhgwg4czm51wh60d8tk86j8"
        }
    },
    "imageable": {
        "namespace": "",
        "maxListeners": 512,
        "imageSizeLimit": 1024,
        "timeouts": {
            "convert": 5000,
            "identify": 100,
            "download": 1000
        },
        "whitelist": {
            "allowedHosts": [
                ".*divante.pl",
                ".*vuestorefront.io",
                ".*localhost"
            ],
            "trustedHosts": [
                ".*divante.pl",
                ".*vuestorefront.io",
                ".*localhost"
            ]
        },
        "keepDownloads": true,
        "maxDownloadCacheSize": 1000,
        "tmpPathRoot": "/tmp"
    },
    "elasticsearch": {
        "host": "localhost",
        "port": "9200",
        "indices": [
            "vue_storefront_catalog",
            "vue_storefront_catalog_it",
            "vue_storefront_catalog_de"
        ]
    }
}
```

### **vue-storefront/config/local.json**
```
{
    "server": {
      "host": "store.localhost",
      "port": 3000,
      "protocol": "https",
      "api": "api",
      "devServiceWorker": false,
      "useOutputCacheTagging": false,
      "useOutputCache": false,
      "outputCacheDefaultTtl": 86400,
      "availableCacheTags": ["product", "category", "home", "checkout", "page-not-found", "compare", "my-account", "P", "C", "error"],
      "invalidateCacheKey": "aeSu7aip",
      "dynamicConfigReload": false,
      "dynamicConfigContinueOnError": false,
      "dynamicConfigExclude": ["ssr", "storeViews", "entities", "localForage", "shipping", "boost", "query"],
      "dynamicConfigInclude": [],
      "elasticCacheQuota": 4096,
      "ssrDisabledFor": {
        "extensions": [".png", ".gif", ".jpg", ".jpeg", ".woff", ".eot", ".woff2", ".ttf", ".svg", ".css", ".js", ".json", ".ico", ".tiff", ".tif", ".raw"]
      }
    },
    "seo": {
      "useUrlDispatcher": true,
      "disableUrlRoutesPersistentCache": true
    },
    "console": {
      "showErrorOnProduction" : false,
      "verbosityLevel": "display-everything"
    },
    "redis": {
      "host": "localhost",
      "port": 6379,
      "db": 0
    },
    "graphql":{
      "host": "localhost",
      "port": 8080
    },
    "api": {
      "url": "https://store.localhost:8080"
    },
    "elasticsearch": {
      "httpAuth": "",
      "host": "/api/catalog",
      "index": "vue_storefront_catalog",
      "min_score": 0.02,
      "csrTimeout": 5000,
      "ssrTimeout": 1000,
      "queryMethod": "GET",
      "disablePersistentQueriesCache": true,
      "searchScoring": {
        "attributes": {
          "attribute_code": {
            "scoreValues": { "attribute_value": { "weight": 1 } }
          }
        },
        "fuzziness": 2,
        "cutoff_frequency":  0.01,
        "max_expansions": 3,
        "minimum_should_match": "75%",
        "prefix_length": 2,
        "boost_mode": "multiply",
        "score_mode": "multiply",
        "max_boost": 100,
        "function_min_score": 1
      },
      "searchableAttributes": {
        "name": {
          "boost": 4
        },
        "sku": {
          "boost": 2
        },
        "category.name": {
          "boost": 1
        }
      }
    },
    "ssr": {
      "templates": {
        "default": "dist/index.html",
        "minimal": "dist/index.minimal.html",
        "basic": "dist/index.basic.html",
        "amp": "dist/index.amp.html"
      },
      "executeMixedinAsyncData": true,
      "initialStateFilter": ["__DEMO_MODE__", "version", "storeView"],
      "useInitialStateFilter": true
    },
    "defaultStoreCode": "",
    "storeViews": {
      "multistore": false,
      "commonCache": true,
      "mapStoreUrlsFor": ["de", "it"],
      "de": {
        "storeCode": "de",
        "disabled": true,
        "storeId": 3,
        "name": "German Store",
        "url": "/de",
        "appendStoreCode": true,
        "elasticsearch": {
          "host": "/api/catalog",
          "index": "vue_storefront_catalog_de"
        },
        "tax": {
          "sourcePriceIncludesTax": false,
          "defaultCountry": "DE",
          "defaultRegion": "",
          "calculateServerSide": true
        },
        "i18n": {
          "fullCountryName": "Germany",
          "fullLanguageName": "German",
          "defaultLanguage": "DE",
          "defaultCountry": "DE",
          "defaultLocale": "de-DE",
          "currencyCode": "EUR",
          "currencySign": "EUR",
          "dateFormat": "HH:mm D-M-YYYY"
        }
      },
      "it": {
        "storeCode": "it",
        "disabled": true,
        "storeId": 4,
        "name": "Italian Store",
        "url": "/it",
        "appendStoreCode": true,
        "elasticsearch": {
          "host": "/api/catalog",
          "index": "vue_storefront_catalog_it"
        },
        "tax": {
          "sourcePriceIncludesTax": false,
          "defaultCountry": "IT",
          "defaultRegion": "",
          "calculateServerSide": true
        },
        "i18n": {
          "fullCountryName": "Italy",
          "fullLanguageName": "Italian",
          "defaultCountry": "IT",
          "defaultLanguage": "IT",
          "defaultLocale": "it-IT",
          "currencyCode": "EUR",
          "currencySign": "EUR",
          "dateFormat": "HH:mm D-M-YYYY"
        }
      }
    },
    "entities": {
      "optimize": true,
      "twoStageCaching": true,
      "optimizeShoppingCart": true,
      "category": {
        "includeFields": [ "id", "*.children_data.id", "*.id", "children_count", "sku", "name", "is_active", "parent_id", "level", "url_key", "url_path", "product_count", "path"],
        "excludeFields": [ "sgn" ],
        "categoriesRootCategorylId": 2,
        "categoriesDynamicPrefetchLevel": 2,
        "categoriesDynamicPrefetch": true
      },
      "attribute": {
        "includeFields": [ "attribute_code", "id", "entity_type_id", "options", "default_value", "is_user_defined", "frontend_label", "attribute_id", "default_frontend_label", "is_visible_on_front", "is_visible", "is_comparable", "tier_prices", "frontend_input" ]
      },
      "productList": {
        "sort": "updated_at:desc",
        "includeFields": [ "type_id", "sku", "product_links", "tax_class_id", "special_price", "special_to_date", "special_from_date", "name", "price", "priceInclTax", "originalPriceInclTax", "originalPrice", "specialPriceInclTax", "id", "image", "sale", "new", "url_path", "url_key", "status", "tier_prices", "configurable_children.sku", "configurable_children.price", "configurable_children.special_price", "configurable_children.priceInclTax", "configurable_children.specialPriceInclTax", "configurable_children.originalPrice", "configurable_children.originalPriceInclTax" ],
        "excludeFields": [ "description", "configurable_options", "sgn", "*.sgn", "msrp_display_actual_price_type", "*.msrp_display_actual_price_type", "required_options" ]
      },
      "productListWithChildren": {
        "includeFields": [ "type_id", "sku", "name", "tax_class_id", "special_price", "special_to_date", "special_from_date", "price", "priceInclTax", "originalPriceInclTax", "originalPrice", "specialPriceInclTax", "id", "image", "sale", "new", "configurable_children.image", "configurable_children.sku", "configurable_children.price", "configurable_children.special_price", "configurable_children.priceInclTax", "configurable_children.specialPriceInclTax", "configurable_children.originalPrice", "configurable_children.originalPriceInclTax", "configurable_children.color", "configurable_children.size", "configurable_children.id", "configurable_children.tier_prices", "product_links", "url_path", "url_key", "status", "tier_prices"],
        "excludeFields": [ "description", "sgn", "*.sgn", "msrp_display_actual_price_type", "*.msrp_display_actual_price_type", "required_options"]
      },
      "review": {
        "excludeFields": ["review_entity", "review_status"]
      },
      "product": {
        "excludeFields": [ "*.msrp_display_actual_price_type", "required_options", "updated_at", "created_at", "attribute_set_id", "options_container", "msrp_display_actual_price_type", "has_options", "stock.manage_stock", "stock.use_config_min_qty", "stock.use_config_notify_stock_qty", "stock.stock_id",  "stock.use_config_backorders", "stock.use_config_enable_qty_inc", "stock.enable_qty_increments", "stock.use_config_manage_stock", "stock.use_config_min_sale_qty", "stock.notify_stock_qty", "stock.use_config_max_sale_qty", "stock.use_config_max_sale_qty", "stock.qty_increments", "small_image", "sgn", "*.sgn"],
        "includeFields": null,
        "useDynamicAttributeLoader": true,
        "standardSystemFields": [
          "description",
          "configurable_options",
          "tsk",
          "custom_attributes",
          "size_options",
          "regular_price",
          "final_price",
          "price",
          "color_options",
          "id",
          "links",
          "gift_message_available",
          "category_ids",
          "sku",
          "stock",
          "image",
          "thumbnail",
          "visibility",
          "type_id",
          "tax_class_id",
          "media_gallery",
          "url_key",
          "url_path",
          "max_price",
          "minimal_regular_price",
          "special_price",
          "minimal_price",
          "name",
          "configurable_children",
          "max_regular_price",
          "category",
          "status",
          "priceTax",
          "priceInclTax",
          "specialPriceTax",
          "specialPriceInclTax",
          "_score",
          "slug",
          "errors",
          "info",
          "erin_recommends",
          "special_from_date",
          "news_from_date",
          "custom_design_from",
          "originalPrice",
          "originalPriceInclTax",
          "parentSku",
          "options",
          "product_option",
          "qty",
          "is_configured"
        ]
      }
    },
    "cart": {
      "thumbnails": {
        "width": 150,
        "height": 150
      },
      "bypassCartLoaderForAuthorizedUsers": true,
      "serverMergeByDefault": true,
      "serverSyncCanRemoveLocalItems": false,
      "serverSyncCanModifyLocalItems": false,
      "synchronize": true,
      "synchronize_totals": true,
      "setCustomProductOptions": true,
      "setConfigurableProductOptions": true,
      "askBeforeRemoveProduct": true,
      "displayItemDiscounts": true,
      "minicartCountType": "quantities",
      "create_endpoint": "/api/cart/create?token={{token}}",
      "updateitem_endpoint": "/api/cart/update?token={{token}}&cartId={{cartId}}",
      "deleteitem_endpoint": "/api/cart/delete?token={{token}}&cartId={{cartId}}",
      "pull_endpoint": "/api/cart/pull?token={{token}}&cartId={{cartId}}",
      "totals_endpoint": "/api/cart/totals?token={{token}}&cartId={{cartId}}",
      "paymentmethods_endpoint": "/api/cart/payment-methods?token={{token}}&cartId={{cartId}}",
      "shippingmethods_endpoint": "/api/cart/shipping-methods?token={{token}}&cartId={{cartId}}",
      "shippinginfo_endpoint": "/api/cart/shipping-information?token={{token}}&cartId={{cartId}}",
      "collecttotals_endpoint": "/api/cart/collect-totals?token={{token}}&cartId={{cartId}}",
      "deletecoupon_endpoint": "/api/cart/delete-coupon?token={{token}}&cartId={{cartId}}",
      "applycoupon_endpoint": "/api/cart/apply-coupon?token={{token}}&cartId={{cartId}}&coupon={{coupon}}"
    },
    "products": {
      "disablePersistentProductsCache": true,
      "useMagentoUrlKeys": true,
      "setFirstVarianAsDefaultInURL": false,
      "configurableChildrenStockPrefetchStatic": false,
      "configurableChildrenStockPrefetchDynamic": false,
      "configurableChildrenStockPrefetchStaticPrefetchCount": 8,
      "filterUnavailableVariants": false,
      "listOutOfStockProducts": true,
      "preventConfigurableChildrenDirectAccess": true,
      "alwaysSyncPlatformPricesOver": false,
      "clearPricesBeforePlatformSync": false,
      "waitForPlatformSync": false,
      "setupVariantByAttributeCode": true,
      "endpoint": "/api/product",
      "defaultFilters": ["color", "size", "price", "erin_recommends"],
      "filterFieldMapping": {
        "category.name": "category.name.keyword"
      },
      "colorMappings": {
        "Melange graphite": "#eeeeee"
      },
      "defaultSortBy": {
        "attribute": "updated_at",
        "order": "desc"
      },
      "sortByAttributes": {
        "Latest": "updated_at",
        "Price: Low to high":"final_price",
        "Price: High to low":"final_price:desc"
      },
      "gallery": {
        "mergeConfigurableChildren": true,
        "imageAttributes": ["image","thumbnail","small_image"],
        "width": 600,
        "height": 744
      },
      "thumbnails": {
        "width": 310,
        "height": 300
      },
      "filterAggregationSize": {
        "default": 10,
        "size": 10,
        "color": 10
      },
      "priceFilters": {
        "ranges": [
          { "from": 0, "to": 50 },
          { "from": 50, "to": 100 },
          { "from": 100, "to": 150 },
          { "from": 150 }
        ]
      }
    },
    "orders": {
      "directBackendSync": true,
      "endpoint": "/api/order",
      "payment_methods_mapping": {
      },
      "offline_orders": {
        "automatic_transmission_enabled": false,
        "notification" : {
          "enabled": true,
          "title" : "Order waiting!",
          "message": "Click here to confirm the order that you made offline.",
          "icon": "/assets/logo.png"
        }
      }
    },
    "localForage": {
      "defaultDrivers": {
        "user": "LOCALSTORAGE",
        "cmspage": "LOCALSTORAGE",
        "cmsblock": "LOCALSTORAGE",
        "carts": "LOCALSTORAGE",
        "orders": "LOCALSTORAGE",
        "wishlist": "LOCALSTORAGE",
        "categories": "LOCALSTORAGE",
        "attributes": "LOCALSTORAGE",
        "elasticCache": "LOCALSTORAGE",
        "claims": "LOCALSTORAGE",
        "syncTasks": "LOCALSTORAGE",
        "ordersHistory": "LOCALSTORAGE",
        "checkoutFieldValues": "LOCALSTORAGE"
      }
    },
    "reviews": {
      "create_endpoint": "/api/review/create"
    },
    "users": {
      "autoRefreshTokens": true,
      "endpoint": "/api/user",
      "history_endpoint": "/api/user/order-history?token={{token}}",
      "resetPassword_endpoint": "/api/user/reset-password",
      "changePassword_endpoint": "/api/user/change-password?token={{token}}",
      "login_endpoint": "/api/user/login",
      "create_endpoint": "/api/user/create",
      "me_endpoint": "/api/user/me?token={{token}}",
      "refresh_endpoint": "/api/user/refresh"
    },
    "stock": {
      "synchronize": true,
      "allowOutOfStockInCart": true,
      "endpoint": "/api/stock"
    },
    "images": {
      "useExactUrlsNoProxy": false,
      "baseUrl": "https://store.localhost/img/",
      "productPlaceholder": "/assets/placeholder.jpg"
    },
    "install": {
      "is_local_backend": true,
      "backend_dir": "../vue-storefront-api"
    },
    "demomode": false,
    "tax": {
      "defaultCountry": "US",
      "defaultRegion": "",
      "sourcePriceIncludesTax": false,
      "calculateServerSide": true
    },
    "shipping": {
      "methods": [
        {
          "method_title": "DPD Courier",
          "method_code": "flatrate",
          "carrier_code": "flatrate",
          "amount": 4,
          "price_incl_tax": 5,
          "default": true,
          "offline": true
        }
      ]
    },
    "syncTasks": {
      "disablePersistentTaskQueue": true
    },
    "i18n": {
      "defaultCountry": "US",
      "defaultLanguage": "EN",
      "availableLocale": ["en-US","de-DE","fr-FR","es-ES","nl-NL", "jp-JP", "ru-RU", "it-IT", "pt-BR", "pl-PL", "cs-CZ"],
      "defaultLocale": "en-US",
      "currencyCode": "USD",
      "currencySign": "$",
      "currencySignPlacement": "preppend",
      "dateFormat": "l LT",
      "fullCountryName": "United States",
      "fullLanguageName": "English",
      "bundleAllStoreviewLanguages": true
    },
    "expireHeaders": {
      "default": "30d",
      "application/json": "24h",
      "image/png": "7d"
    },
    "newsletter": {
      "endpoint": "/api/ext/mailchimp-subscribe/subscribe"
    },
    "mailer": {
      "endpoint": {
        "send": "/api/ext/mail-service/send-email",
        "token": "/api/ext/mail-service/get-token"
      },
      "contactAddress": "contributors@vuestorefront.io",
      "sendConfirmation": true
    },
    "theme": "@vue-storefront/theme-default",
    "analytics": {
      "id": false
    },
    "googleTagManager": {
      "id": false,
      "debug": true
    },
    "hotjar": {
      "id": false
    },
    "cms": {
      "endpoint": "/api/ext/cms-data/cms{{type}}/{{cmsId}}",
      "endpointIdentifier": "/api/ext/cms-data/cms{{type}}Identifier/{{cmsIdentifier}}/storeId/{{storeId}}"
    },
    "cms_block": {
      "max_count": 500
    },
    "cms_page": {
      "max_count": 500
    },
    "usePriceTiers": false,
    "useZeroPriceProduct": true,
    "query": {
      "inspirations": {
        "filter": [
          {
            "key": "category.name",
            "value" : { "eq": "Performance Fabrics" }
          }
        ]
      },
      "newProducts": {
        "filter": [
          {
            "key": "category.name",
            "value" : { "eq": "Tees" }
          }
        ]
      },
      "coolBags": {
        "filter": [
          {
            "key": "category.name",
            "value" : { "eq": "Women" }
          }
        ]
      },
      "bestSellers": {
        "filter": [
          {
            "key": "category.name",
            "value" : { "eq": "Tees" }
          }
        ]
      }
    }
}

```

Please help so that VSF troubleshooting does not consume the rest of my life.

**Comment by pkarw** [comment]
Hi there! I think this issue is more devops than vsf related and it’s apparently not a vsf bug. So I’m changing the label to question
