### ISSUE TITLE
Run production mode without TS

### ISSUE THREAD

**Issue by andrzejewsky** [DivanteLtd/vue-storefront#3981]
We have several issues (eg. https://github.com/DivanteLtd/vue-storefront/pull/3851) with running server.ts using pm2. I think the best solution will be building server as well and run it without typescript. Even pm2 [docs](https://doc.pm2.io/en/runtime/integration/transpilers/) doesn't recommend to use transpilers on the production environment

**Comment by pkarw** [comment]
@andrzejewsky this same issue may affect vs-api and sf-api

**Comment by gukandrew** [comment]
After commit d5060b5881901530a1c5438880b91fe9c72d9cc8 we got the error on production while starting pm2:
command
```
yarn cross-env NODE_ENV=production TS_NODE_PROJECT=\"tsconfig-build.json\" pm2 start ecosystem.json --no-daemon
```

Got error:
```
$ /home/user/vue-storefront/node_modules/.bin/cross-env NODE_ENV=production 'TS_NODE_PROJECT="tsconfig-build.json"' pm2 start ecosystem.json --no-daemon
pm2 launched in no-daemon mode (you can add DEBUG="*" env variable to get more messages)
[2020-02-14 15:57:38] PM2 log: Launching in no daemon mode
[2020-02-14 15:57:38] PM2 log: [PM2][WARN] Applications server not running, starting...
[2020-02-14 15:57:38] PM2 log: Starting execution sequence in -cluster mode- for app name:server id:0
[2020-02-14 15:57:38] PM2 log: App name:server id:0 online
[2020-02-14 15:57:38] PM2 log: Starting execution sequence in -cluster mode- for app name:server id:1
[2020-02-14 15:57:39] PM2 log: App name:server id:1 online
[2020-02-14 15:57:39] PM2 log: Starting execution sequence in -cluster mode- for app name:server id:2
[2020-02-14 15:57:39] PM2 log: App name:server id:2 online
[2020-02-14 15:57:39] PM2 log: Starting execution sequence in -cluster mode- for app name:server id:3
[2020-02-14 15:57:39] PM2 log: App name:server id:3 online
[2020-02-14 15:57:39] PM2 log: [PM2] App [server] launched (4 instances)
[2020-02-14 15:57:39] PM2 log: ┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬───────┬───────────┬───────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu   │ mem       │ user  │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼───────┼───────────┼───────┼──────────┤
│ server   │ 0  │ cluster │ 13477 │ online │ 0       │ 0s     │ 2266% │ 83.0 MB   │ admin │ disabled │
│ server   │ 1  │ cluster │ 13483 │ online │ 0       │ 0s     │ 63%   │ 81.9 MB   │ admin │ disabled │
│ server   │ 2  │ cluster │ 13506 │ online │ 0       │ 0s     │ 58%   │ 53.9 MB   │ admin │ disabled │
│ server   │ 3  │ cluster │ 13531 │ online │ 0       │ 0s     │ 55%   │ 36.2 MB   │ admin │ disabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴───────┴───────────┴───────┴──────────┘
[2020-02-14 15:57:39] PM2 log:  Use `pm2 show <id|name>` to get more details about an app
[2020-02-14 15:57:39] PM2 log: [--no-daemon] Continue to stream logs
[2020-02-14 15:57:39] PM2 log: [--no-daemon] Exit on target PM2 exit pid=13467
15:57:40 0|server   | Error: Cannot find module '/home/user/vue-storefront/start'
15:57:40 0|server   |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
15:57:40 0|server   |     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
15:57:40 0|server   |     at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
15:57:40 0|server   |     at Object.<anonymous> (/home/user/vue-storefront/node_modules/ts-node/src/bin.ts:157:12)
15:57:40 0|server   |     at Module._compile (internal/modules/cjs/loader.js:678:30)
15:57:40 0|server   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
15:57:40 0|server   |     at Module.load (internal/modules/cjs/loader.js:589:32)
15:57:40 0|server   |     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
15:57:40 0|server   |     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
15:57:40 0|server   |     at /home/user/vue-storefront/node_modules/pm2/lib/ProcessContainer.js:331:23
```

**Comment by andrzejewsky** [comment]
@gukandrew can you give me more details about runtime environment (node version, npm version, os etc.) - because it totally works for me and for people who used to have a problem with ts-node

**Comment by gukandrew** [comment]
Sure:
Sure here is my dev machine setup:
```
node -v
v12.16.0

yarn -v
1.22.0

npm -v
6.13.2
lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        18.1.3
Codename:       Juhraya
```

Here is staging os (in prod mode):
```
/var/www # node -v && yarn -v && npm -v
v10.19.0
1.21.1
6.13.4

/var/www # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.3
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

Got same error on both environments...

**Comment by andrzejewsky** [comment]
@gibkigonzo can you check this out?

**Comment by gibkigonzo** [comment]
hey, I get this error when I add `--no-daemon` which is weird. I will try to find out why this happen

**Comment by gukandrew** [comment]
@gibkigonzo, yep that's why I mentioned `--no-daemon`, but it's hidden under scroll in my post.
The thing is in that flag - it's required for prod (the healthcheck is watching for shell output, so if try to create demonized process this will cause no output and circular redeploy of container)

**Comment by pkarw** [comment]
@gukandrew can you please check adding the script path to the `pm2 start --no-deamon` instead of `ecosystem.json` or changing the script path to absolute in the `ecosystem.json` or adding kind of `cwd` to current directory before this call?

**Comment by pkarw** [comment]
@gibkigonzo can you please share your today’s findings on this issue?

**Comment by gibkigonzo** [comment]
@gukandrew I think that problem is related with pm2. Here is issue https://github.com/Unitech/pm2/issues/4613
You can make this work by running `pm2 reset all` before `pm2 start --no-daemon`

**Comment by haelbichalex** [comment]
We are facing this issue as well while running VSF in docker after upgrading to v1.11.2

**Comment by haelbichalex** [comment]
Adding `pm2 reset all` for the `start` command in `package.json` fixed it in our docker setup!
```
"start": "cross-env NODE_ENV=production TS_NODE_PROJECT=\"tsconfig-build.json\" pm2 reset all && pm2 start ecosystem.json $PM2_ARGS"
```

**Comment by Ogek** [comment]
Adding `pm2 reset all` to the `start` command fixed the issue also for me. Thanks 👍
