### ISSUE TITLE
Error during magento 2 integration - Snowdog module

### ISSUE THREAD

**Issue by WestArjan** [DivanteLtd/vue-storefront#4290]
Is the snowdog module a requirement for vue storefront to work properly with Magento 2?
```
/rest/V1/snowdog/cmsBlock/search?searchCriteria=undefined

node_redis: Warning: Redis server does not require a password, but a password was supplied.

node_redis: Warning: Redis server does not require a password, but a password was supplied.

node_redis: Warning: Redis server does not require a password, but a password was supplied.

[34mdebug[39m: Response received.

[31merror[39m: API call failed: Request does not match any route.

2020-04-27T12:51:00.373Z - [31merror[39m:  
{
  message: [32m'Request does not match any route.'[39m,
  stack: [32m'Error: Request does not match any route.\n'[39m +
    [32m'    at /home/awest/Documents/Stage/Vue/vuenpm1/api/node_modules/mage2vuestorefront/src/adapters/magento/cms_block.js:27:19\n'[39m +
    [32m'    at processTicksAndRejections (internal/process/task_queues.js:97:5)'[39m
}

2020-04-27T12:51:00.381Z - [32minfo[39m: Task done! Exiting in 30s...

Done! Bye Bye!
Done in 1231.92s.
```

**Comment by gibkigonzo** [comment]
vsf use https://github.com/DivanteLtd/mage2vuestorefront when doing import (yarn mage2vs import). This module is required for cms blocks and pages.
