### ISSUE TITLE
Error elasticsearch on fresh install

### ISSUE THREAD

**Issue by WestArjan** [DivanteLtd/vue-storefront#4383]
On trying a new installation of vue storefront I get following error in the logs for the vue storefront application : 

```
[search] Can not connect the vue-storefront-api / ElasticSearch instance! Error: {"code":500,"result":{"diagnosticText":"src/processor/default.ts(25,48): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'string | ParsedQs | string[] | ParsedQs[] | ((searchString: string, position?: number) => number) | ((searchElement: string, fromIndex?: number) => number) | ((searchElement: ParsedQs, fromIndex?: number) => number)' has no compatible call signatures.\n","diagnosticCodes":[2349]}}
    at SearchAdapter.exports.modules../core/lib/search/adapter/api/searchAdapter.ts.SearchAdapter.handleResult (vsf-search-adapter-0.server-bundle.js:547:23)
    at Object.resultProcessor (vsf-search-adapter-0.server-bundle.js:582:30)
    at server-bundle.js:3204:92
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:68736) UnhandledPromiseRejectionWarning: Error: {"code":500,"result":{"diagnosticText":"src/processor/default.ts(25,48): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'string | ParsedQs | string[] | ParsedQs[] | ((searchString: string, position?: number) => number) | ((searchElement: string, fromIndex?: number) => number) | ((searchElement: ParsedQs, fromIndex?: number) => number)' has no compatible call signatures.\n","diagnosticCodes":[2349]}}
(node:68736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 49)
Result from ES for cb5dc76b0d10e18eb928348b3ba27ccbeff7921d91243089df97f350 (product),  ms=3968 null
```

And on the vue storefront api logs  i get : 
```
[0mGET /api/catalog/vue_storefront_catalog/attribute/_search?_source_include=activity%2Cattribute_code%2Cattribute_id%2Cdefault_frontend_label%2Cdefault_value%2Centity_type_id%2Cfrontend_input%2Cfrontend_label%2Cid%2Cis_user_defined%2Cis_visible_on_front%2Cis_visible%2Cis_comparable%2Coptions%2Ctier_prices&from=0&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22terms%22%3A%7B%22attribute_code%22%3A%5B%22color%22%2C%22erin_recommends%22%2C%22price%22%2C%22size%22%2C%22activity%22%2C%22final_price%22%2C%22id%22%2C%22image%22%2C%22name%22%2C%22new%22%2C%22original_price%22%2C%22original_price_incl_tax%22%2C%22price_incl_tax%22%2C%22product_links%22%2C%22sale%22%2C%22sku%22%2C%22special_price%22%2C%22special_price_incl_tax%22%2C%22special_from_date%22%2C%22special_to_date%22%2C%22status%22%2C%22tax_class_id%22%2C%22tier_prices%22%2C%22type_id%22%2C%22url_path%22%2C%22url_key%22%5D%7D%7D%7D%7D%7D&size=150&sort= [31m500[0m 1476.887 ms - 437[0m
[0mGET /api/catalog/vue_storefront_catalog/product/_search?_source_exclude=attribute_set_id%2Ccreated_at%2Chas_options%2Cmsrp_display_actual_price_type%2C%2A.msrp_display_actual_price_type%2Coptions_container%2Crequired_options%2Csmall_image%2Cstock.enable_qty_increments%2Cstock.is_decimal_divided%2Cstock.manage_stock%2Cstock.notify_stock_qty%2Cstock.qty_increments%2Cstock.show_default_notification_message%2Cstock.stock_id%2Cstock.stock_status_changed_auto%2Cstock.use_config_qty_increments%2Cstock.use_config_min_qty%2Cstock.use_config_notify_stock_qty%2Cstock.use_config_backorders%2Cstock.use_config_enable_qty_inc%2Cstock.use_config_manage_stock%2Cstock.use_config_min_sale_qty%2Cstock.use_config_max_sale_qty%2Csgn%2C%2A.sgn%2Cupdated_at&from=0&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22category.name.keyword%22%3A%5B%22Tees%22%5D%7D%7D%2C%7B%22terms%22%3A%7B%22visibility%22%3A%5B2%2C3%2C4%5D%7D%7D%2C%7B%22terms%22%3A%7B%22status%22%3A%5B0%2C1%5D%7D%7D%5D%7D%7D%7D%7D%7D&size=8&sort=created_at%3Adesc [32m200[0m 3706.304 ms - 183721[0m
No additional data adapter for category
[0mGET /api/catalog/vue_storefront_catalog/category/_search?_source_exclude=sgn&_source_include=children_count%2Cid%2Cis_active%2Clevel%2Cname%2Cparent_id%2Cpath%2Cposition%2Cproduct_count%2Csku%2Curl_key%2Curl_path%2C%2A.children_data.id%2C%2A.id&from=0&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22level%22%3A%5B2%5D%7D%7D%2C%7B%22terms%22%3A%7B%22is_active%22%3A%5Btrue%5D%7D%7D%5D%7D%7D%7D%7D%7D&size=4000&sort=position%3Aasc [31m500[0m 113.964 ms - 437[0m
No additional data adapter for attribute
[0mGET /api/catalog/vue_storefront_catalog/attribute/_search?_source_include=activity%2Cattribute_code%2Cattribute_id%2Cdefault_frontend_label%2Cdefault_value%2Centity_type_id%2Cfrontend_input%2Cfrontend_label%2Cid%2Cis_user_defined%2Cis_visible_on_front%2Cis_visible%2Cis_comparable%2Coptions%2Ctier_prices&from=0&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22terms%22%3A%7B%22attribute_code%22%3A%5B%22color%22%2C%22erin_recommends%22%2C%22price%22%2C%22size%22%2C%22activity%22%2C%22final_price%22%2C%22id%22%2C%22image%22%2C%22name%22%2C%22new%22%2C%22original_price%22%2C%22original_price_incl_tax%22%2C%22price_incl_tax%22%2C%22product_links%22%2C%22sale%22%2C%22sku%22%2C%22special_price%22%2C%22special_price_incl_tax%22%2C%22special_from_date%22%2C%22special_to_date%22%2C%22status%22%2C%22tax_class_id%22%2C%22tier_prices%22%2C%22type_id%22%2C%22url_path%22%2C%22url_key%22%5D%7D%7D%7D%7D%7D&size=150&sort= [31m500[0m 49.753 ms - 437[0m
[0mOPTIONS /api/catalog/vue_storefront_catalog/attribute/_search?_source_include=activity%2Cattribute_code%2Cattribute_id%2Cdefault_frontend_label%2Cdefault_value%2Centity_type_id%2Cfrontend_input%2Cfrontend_label%2Cid%2Cis_user_defined%2Cis_visible_on_front%2Cis_visible%2Cis_comparable%2Coptions%2Ctier_prices&from=0&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22terms%22%3A%7B%22attribute_code%22%3A%5B%22color%22%2C%22erin_recommends%22%2C%22price%22%2C%22size%22%2C%22activity%22%2C%22final_price%22%2C%22id%22%2C%22image%22%2C%22name%22%2C%22new%22%2C%22original_price%22%2C%22original_price_incl_tax%22%2C%22price_incl_tax%22%2C%22product_links%22%2C%22sale%22%2C%22sku%22%2C%22special_price%22%2C%22special_price_incl_tax%22%2C%22special_from_date%22%2C%22special_to_date%22%2C%22status%22%2C%22tax_class_id%22%2C%22tier_prices%22%2C%22type_id%22%2C%22url_path%22%2C%22url_key%22%5D%7D%7D%7D%7D%7D&size=150&sort= [32m204[0m 3.237 ms - 0[0m
No additional data adapter for attribute
[0mGET /api/catalog/vue_storefront_catalog/attribute/_search?_source_include=activity%2Cattribute_code%2Cattribute_id%2Cdefault_frontend_label%2Cdefault_value%2Centity_type_id%2Cfrontend_input%2Cfrontend_label%2Cid%2Cis_user_defined%2Cis_visible_on_front%2Cis_visible%2Cis_comparable%2Coptions%2Ctier_prices&from=0&request=%7B%22query%22%3A%7B%22bool%22%3A%7B%22filter%22%3A%7B%22terms%22%3A%7B%22attribute_code%22%3A%5B%22color%22%2C%22erin_recommends%22%2C%22price%22%2C%22size%22%2C%22activity%22%2C%22final_price%22%2C%22id%22%2C%22image%22%2C%22name%22%2C%22new%22%2C%22original_price%22%2C%22original_price_incl_tax%22%2C%22price_incl_tax%22%2C%22product_links%22%2C%22sale%22%2C%22sku%22%2C%22special_price%22%2C%22special_price_incl_tax%22%2C%22special_from_date%22%2C%22special_to_date%22%2C%22status%22%2C%22tax_class_id%22%2C%22tier_prices%22%2C%22type_id%22%2C%22url_path%22%2C%22url_key%22%5D%7D%7D%7D%7D%7D&size=150&sort= [31m500[0m 75.538 ms - 437[0m
[0mGET /api/catalog/vue_storefront_catalog/product/_search?q=bag [32m200[0m 95.972 ms - 78599[0m
```

When testing ` curl -i http://localhost:8080/api/catalog/vue_storefront_catalog/product/_search?q=bag&size=50&from=0` however, i do get a response filled with data that is migrated from magento. Since this is a fresh install with the only thing done to it is the CLI instructions given on the vue storefront documentation, what could have gone wrong here? This issue seems to persist on every new installation.

**Comment by gibkigonzo** [comment]
hey, it's not ES error but it's a same error as here https://github.com/DivanteLtd/vue-storefront/issues/4275 You need to use yarn to install project instead of npm. There is bug in cli which uses npm to install backend, here is fix https://github.com/DivanteLtd/vue-storefront/pull/4292

You get product data because it uses different processor. Rest entities use default processor where is used query.

So when you install project by npm (cli) then you will get newest `@types/express-serve-static-core` where in last month was added breaking change. We need to add typing for query to get this error fixed. I will move it to vsf-api repo.
