### ISSUE TITLE
NodeJS 6.x is not supported

### ISSUE THREAD

**Issue by EliasKotlyar** [DivanteLtd/vue-storefront#773]
I tried to install it on the normal NodeJS 6.x Version which is stock on Ubuntu. Unfortunately, it fails with the following error:
```
 npm run installer

> vue-storefront@0.0.0 installer /home/eko/Schreibtisch/vue-storefront
> node ./core/scripts/installer

/home/eko/Schreibtisch/vue-storefront/core/scripts/installer.js:652
  inquirer.prompt(questions).then(async function (answers) {
                                  ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

npm ERR! Linux 4.14.2-041402-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "installer"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! vue-storefront@0.0.0 installer: `node ./core/scripts/installer`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-storefront@0.0.0 installer script 'node ./core/scripts/installer'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-storefront package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./core/scripts/installer
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-storefront
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-storefront
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eko/Schreibtisch/vue-storefront/npm-debug.log

```

After upgrading to NodeJS 8.0 everyhing is running fine.

Is this intended? According to the requirements, there is no minimum version of NodeJS required:
https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Installing%20on%20Linux%20and%20MacOS.md

**Comment by pkarw** [comment]
This is not an issue, this is intended. We'll add minimum node version to package.json

**Comment by EliasKotlyar** [comment]
Thanks you! I provided a documentation fix.
