### ISSUE TITLE
Installation fails if not run with "sudo"

### ISSUE THREAD

**Issue by EliasKotlyar** [DivanteLtd/vue-storefront#774]
If you run the "npm run installer" without sudo, it fails:
```

> vue-storefront@0.0.0 build /home/eko/Schreibtisch/vue-storefront
> rimraf dist && npm run build:client && npm run build:server

/home/eko/Schreibtisch/vue-storefront/node_modules/rimraf/bin.js:47
      throw er
      ^

Error: EACCES: permission denied, unlink 'dist/app.6c1293f4f156156e0828.js'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-storefront@0.0.0 build: `rimraf dist && npm run build:client && npm run build:server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-storefront@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eko/.npm/_logs/2018-02-28T12_59_52_544Z-debug.log


eko@eko-GE62VR-6RF:~$ cat  /home/eko/.npm/_logs/2018-02-28T12_59_52_544Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/home/eko/Schreibtisch/vue-storefront/node_modules/.bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.7.1
3 info using node@v8.9.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vue-storefront@0.0.0~prebuild: vue-storefront@0.0.0
6 info lifecycle vue-storefront@0.0.0~build: vue-storefront@0.0.0
7 verbose lifecycle vue-storefront@0.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle vue-storefront@0.0.0~build: PATH: /home/eko/Schreibtisch/vue-storefront/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/eko/Schreibtisch/vue-storefront/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/eko/Schreibtisch/vue-storefront/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle vue-storefront@0.0.0~build: CWD: /home/eko/Schreibtisch/vue-storefront
10 silly lifecycle vue-storefront@0.0.0~build: Args: [ '-c',
10 silly lifecycle   'rimraf dist && npm run build:client && npm run build:server' ]
11 silly lifecycle vue-storefront@0.0.0~build: Returned: code: 1  signal: null
12 info lifecycle vue-storefront@0.0.0~build: Failed to exec build script
13 verbose stack Error: vue-storefront@0.0.0 build: `rimraf dist && npm run build:client && npm run build:server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/eko/Schreibtisch/vue-storefront/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/eko/Schreibtisch/vue-storefront/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid vue-storefront@0.0.0
15 verbose cwd /home/eko/Schreibtisch/vue-storefront
16 verbose Linux 4.14.2-041402-generic
17 verbose argv "/usr/bin/node" "/home/eko/Schreibtisch/vue-storefront/node_modules/.bin/npm" "run" "build"
18 verbose node v8.9.4
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error vue-storefront@0.0.0 build: `rimraf dist && npm run build:client && npm run build:server`
22 error Exit status 1
23 error Failed at the vue-storefront@0.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by thedamianmason** [comment]
This issue has plagued every instance i've tried, the installer just doesn't seem to work using Ubuntu 16.04, Node v8.9.4, Docker v12.17.12.1-ce.

**Comment by pkarw** [comment]
@akbarik could you test it, as far as I remember you work on Ubuntu?

**Comment by pkarw** [comment]
The issue above (regarding the output) points to problem with removing /dist/* - because of permissions. By some reason the content of the folder must have been filled on super user permissions (have you built the project even once using audio before)?

It’s not related to installer I belive

@thedamianmason could you explain some more on the installer problems - maybe you could paste some logs?

**Comment by thedamianmason** [comment]
@pkarw @akbarik I gave up on Ubuntu. Debian works like a charm.

**Comment by akbarik** [comment]
Hi @thedamianmason and @EliasKotlyar! Can you guys please send me the result of running these 2 commands in console?
1. ls -l <you vue-storefront directory>
2. groups <your user's name>
Thanks in advance!

**Comment by thedamianmason** [comment]
@akbarik 
1.
-rwxrwxrwx   CODE_OF_CONDUCT.md
drwxrwxrwx   config
-rwxrwxrwx   CONTRIBUTING.md
drwxrwxrwx   core
drwxrwxrwx   doc
-rwxrwxrwx   LICENSE
drwxrwxrwx  node_modules
-rwxrwxrwx   package.json
-rwxrwxrwx   package-lock.json
-rwxrwxrwx   README.md
drwxrwxrwx   src
drwxrwxrwx   test

2. adm cdrom sudo dip www-data plugdev lxd lpadmin docker

**Comment by akbarik** [comment]
Thanks, @thedamianmason! 
Are you sure you get the same error as @EliasKotlyar posted? In your case there's no dist folder and therefore npm run installer shouldn't give you that error.

**Comment by akbarik** [comment]
Any changes on this issue? Is it still relevant?

**Comment by EliasKotlyar** [comment]
@akbarik : I tried to reproduce my error again, but now everything working fine. I suppose that you should not run "npm install" with sudo.

**Comment by pkarw** [comment]
Ok! Thanks for retesting, im closing the issue for now
